{
  "hash": "542ce9faf05683276563dff5e89422f2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Content Association using Market Basket Analysis\"\nauthor:\n  - name: Christel Lacaze Swift\n    affiliation: BBC\n    email: christel.swift@bbc.co.uk\n    attributes:\n        corresponding: true\nabstract: |\n  Finding prgrammes that have a strong affinity can be done using Market Basket Analysis (also called Frequent itemset analysis or Affinity anlaysis), an approach first developed for physical grocery stores to understand items that are frequently bought together in the shame shopping trip.\ndate: 2025-07-01\ncategories: [content association, market basket analysis, graph networks]\nkeywords: \n  - content association\n  - market basket analysis \n  - graph networks\ndescription: >\n  Applying Market Basket Analysis and Graph Networks to show the strength of association between programmes.\nformat: html\nbibliography: bibliography.bib\ntoc: true\nnumber-sections: true\nimage: \"killing_eve_star.png\"\n---\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressPackageStartupMessages(library(tidyverse))\nlibrary(recommenderlab) # to use the MovieLense dataset\nlibrary(janitor) # to use the clean_names function\nlibrary(visNetwork) # to create the network graph\n\noptions(java.parameters = c(\"-XX:+UseConcMarkSweepGC\", \"-Xmx32g\"))\ngc()\n\ntheme_set(theme_classic()) # sets the ggplot theme for the session\noptions(scipen = 999) # so that numbers don't display with the exponent\noptions(dplyr.summarise.inform = FALSE) # to suppress annoying grouping warning\n```\n:::\n\n\nIn the age of expanding online catalogue availability, recommendation engines were developed to help find the most relevant content for users. These rely on large datasets of users interactions with items, for example viewers history on subscription online video platforms such as Netflix. The most commonly used approaches are based on collaborative filtering using matrix factorization such as ALS, see [@zhou2008].\n\nIn this post, we will see how we can calculate association between programmes using a different approach based on **Market Basket Analysis**, and how we can visualise the results with **Network Graphs**.\n\n# a quick review of Market Basket Analysis\n\nAs the name suggests, this approach was developed to understand what people tend to buy together on a shopping trip, i.e. what ends up in their groceries baskets. By finding sets of items that are often bought together, a physical store can re-arrange their layout and place frequent item sets in close proximity.\n\nBy extension, the same applies to online stores in the form of prompted recommendations, such as \"people who bought this item also bought...\".\n\nFor a full explanation of this topic using R's arules package, please check [@arules].\n\nMarket Basket metrics are derived from measuring conditional probabilities. In the simple setting of just looking at pairs of items (itemset size = 2), if we have items A and B, for example eggs and bacon, then:\\\n- $\\text{support} = P(A \\text{AND} B)$ = joint probability.\\\n- $\\text{confidence} = P(B/A)$ = conditional probability.\\\n- $\\text{lift} = P(A \\text{AND} B)/[P(A)*P(B)]$ = deviation from independent probabilities.\n\nBoth the support and the lift are symmetrical measures: support(A,B) = support(B,A). However the confidence is not symmetrical.\n\nThe lift can take any values between $] -\\infty, +\\infty[$.\\\nA lift of 1 means there is no association, the 2 events are independent.\\\nA lift \\< 1 means there is a negative association between the 2 events: buying one makes you less likely to buy the other.\\\nA lift \\> 1 means there is a positive association between the 2 events: buying one makes you more likely to buy the other.\n\n# applying to the MovieLense dataset\n\nTo demonstrate how to find films that are strongly associated, we will use the MovieLense dataset that is made available in the R package `recommenderlab`. It contains about 100,000 ratings from 943 users on 1664 movies.\n\n## preparing the dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"MovieLense\")\nstr(MovieLense)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFormal class 'realRatingMatrix' [package \"recommenderlab\"] with 2 slots\n  ..@ data     :Formal class 'dgCMatrix' [package \"Matrix\"] with 6 slots\n  .. .. ..@ i       : int [1:99392] 0 1 4 5 9 12 14 15 16 17 ...\n  .. .. ..@ p       : int [1:1665] 0 452 583 673 882 968 994 1386 1605 1904 ...\n  .. .. ..@ Dim     : int [1:2] 943 1664\n  .. .. ..@ Dimnames:List of 2\n  .. .. .. ..$ : chr [1:943] \"1\" \"2\" \"3\" \"4\" ...\n  .. .. .. ..$ : chr [1:1664] \"Toy Story (1995)\" \"GoldenEye (1995)\" \"Four Rooms (1995)\" \"Get Shorty (1995)\" ...\n  .. .. ..@ x       : num [1:99392] 5 4 4 4 4 3 1 5 4 5 ...\n  .. .. ..@ factors : list()\n  ..@ normalize: NULL\n```\n\n\n:::\n:::\n\n\nThe data is stored as a realRatingMatrix object so we first turn it into a dataframe:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfilms_rld <- summary(MovieLense@data) %>% as.data.frame()\n\nnames(films_rld) <- c(\"user_id\", \"film_id\", \"rating\")\n\nhead(films_rld)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  user_id film_id rating\n1       1       1      5\n2       2       1      4\n3       5       1      4\n4       6       1      4\n5      10       1      4\n6      13       1      3\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_users <- n_distinct(films_rld$user_id)\n\nfilms_rld %>% \n  summarise(\n    n_rows = n(),\n    n_users = n_distinct(user_id),\n    n_progs = n_distinct(film_id)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  n_rows n_users n_progs\n1  99392     943    1664\n```\n\n\n:::\n:::\n\n\nLet's keep the films id and name in a separate dataset:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfilm_ids <- data.frame(\n  id = 1:length(unlist(MovieLense@data@Dimnames[2]) ),\n  name = unlist(MovieLense@data@Dimnames[2]) \n) \n\nhead(film_ids)  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  id                                                 name\n1  1                                     Toy Story (1995)\n2  2                                     GoldenEye (1995)\n3  3                                    Four Rooms (1995)\n4  4                                    Get Shorty (1995)\n5  5                                       Copycat (1995)\n6  6 Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)\n```\n\n\n:::\n:::\n\n\nThe top ten most watched films are:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfilms_rld %>% \n  group_by(film_id) %>% \n  summarise(reach = n()) %>% \n  arrange(desc(reach)) %>% \n  head(10) %>% \n  left_join(\n    film_ids %>% \n      rename(film_id = id),\n    by = \"film_id\"\n  ) %>% \n  select(name, film_id, reach)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 3\n   name                          film_id reach\n   <chr>                           <int> <int>\n 1 Star Wars (1977)                   50   583\n 2 Contact (1997)                    258   509\n 3 Fargo (1996)                      100   508\n 4 Return of the Jedi (1983)         181   507\n 5 Liar Liar (1997)                  293   485\n 6 English Patient, The (1996)       285   481\n 7 Scream (1996)                     287   478\n 8 Toy Story (1995)                    1   452\n 9 Air Force One (1997)              299   431\n10 Independence Day (ID4) (1996)     121   429\n```\n\n\n:::\n:::\n\n\nLet's check the distribution of ratings and of the number of items per user:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfilms_rld %>% \n  group_by(rating) %>% \n  summarise(n = n()) %>% \n  mutate(pc = n / sum(n)) %>% \n  ggplot(aes(x = rating, y = pc)) +\n  geom_bar(stat = \"identity\", fill = \"darkorange\") +\n  scale_y_continuous(labels = scales::percent) +\n  labs(title = \"distribution of the ratings\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nJudging from the distribution of ratings, we'll take ratings = 4 or 5 to indicate a positive rating.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntemp <- films_rld %>% \n  group_by(user_id) %>% \n  summarise(n_progs = n())\n\ntemp %>% \n  group_by(n_progs) %>% \n  summarise(n_users = n()) %>% \n  ggplot(aes(x = n_progs, y = n_users)) +\n  geom_bar(stat = \"identity\", fill = \"slateblue\") +\n  labs(title = \"distribution of the number of programmes per user\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(temp$n_progs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   19.0    32.0    64.0   105.4   147.5   735.0 \n```\n\n\n:::\n:::\n\n\nIn this dataset each user has rated at least 19 films, and up to 735.\n\nLet's filter the dataset based on ratings $\\ge$ 4.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfilms_rld <- films_rld %>% \n  filter(rating >= 4)\n\nfilms_rld %>% \n  summarise(\n    n_rows = n(),\n    n_users = n_distinct(user_id),\n    n_progs = n_distinct(film_id)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  n_rows n_users n_progs\n1  55024     942    1433\n```\n\n\n:::\n:::\n\n\nBy removing negative ratings, we are left with about 55k interactions.\n\nThe `MovieLenseMeta` dataset contains the film genres but each film can have more than one:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfilm_genres <- MovieLenseMeta %>% \n  select(-year, -url, -unknown) %>% \n  clean_names() %>% \n  mutate(id = row_number()) %>% \n  # bring all the genres together into one string:\n  unite(\"genre\", action:western, remove = FALSE) %>% \n  pivot_longer(action:western) %>% \n  filter(value == 1) %>% \n  select(-value) %>% \n  group_by(id, title, genre) %>% \n  summarise(genres = str_c(name, collapse = \", \"))\n\nhead(film_genres)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n# Groups:   id, title [6]\n     id title                                                genre        genres\n  <int> <chr>                                                <chr>        <chr> \n1     1 Toy Story (1995)                                     0_0_1_1_1_0… anima…\n2     2 GoldenEye (1995)                                     1_1_0_0_0_0… actio…\n3     3 Four Rooms (1995)                                    0_0_0_0_0_0… thril…\n4     4 Get Shorty (1995)                                    1_0_0_0_1_0… actio…\n5     5 Copycat (1995)                                       0_0_0_0_0_1… crime…\n6     6 Shanghai Triad (Yao a yao yao dao waipo qiao) (1995) 0_0_0_0_0_0… drama \n```\n\n\n:::\n:::\n\n\n## calculating the lift\n\nWe can now calculate the lift between all pairs of films. Recall that the lift measures the deviation from the assumption of independence, so to calculate the lift between films A and B, we will need:\n\n$P(A)=\\cfrac{\\text{\\# of users who watched A}}{\\text{\\# of users}}$\n\n$P(B)=\\cfrac{\\text{\\# of users who watched B}}{\\text{\\# of users}}$\n\n$P(A \\cap B)=\\cfrac{\\text{\\# of users who watched A AND B}}{\\text{\\# of users}}$\n\nAs we have 1433 films, this leads to 1433 \\* 1432 / 2 = 1,026,028 possible pairs of distinct items.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall_pairs_summary <- films_rld %>% \n  rename(item1 = film_id) %>% \n  select(user_id, item1) %>% \n  full_join(\n    films_rld %>% \n      rename(item2 = film_id) %>% \n      select(user_id, item2),\n    by = \"user_id\",\n    relationship = \"many-to-many\"\n  ) %>% \n  group_by(item1, item2) %>% \n  summarise(\n    n = n(),\n    pc = n / n_users\n    ) %>% \n  ungroup()\n\nhead(all_pairs_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  item1 item2     n      pc\n  <int> <int> <int>   <dbl>\n1     1     1   321 0.340  \n2     1     2    30 0.0318 \n3     1     3    19 0.0201 \n4     1     4    64 0.0679 \n5     1     5    24 0.0255 \n6     1     6     7 0.00742\n```\n\n\n:::\n:::\n\n\nThe first entry is simply the reach of item 1, then for item1 != item2, this shows the joint reach of the 2 items, i.e. the **support**. We can now calculate the **confidence** = P(B/A):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall_pairs_summary <- all_pairs_summary %>% \n  # add n1:\n  left_join(\n    all_pairs_summary %>% \n      filter(item1 == item2) %>% \n      rename(n1 = n) %>% \n      select(item1, n1),\n      by = \"item1\"\n  ) %>% \n  # add n2:\n  left_join(\n    all_pairs_summary %>% \n      filter(item1 == item2) %>% \n      rename(n2 = n) %>% \n      select(item2, n2),\n      by = \"item2\"\n  ) %>% \n  # confidence(A, B) = P(B / A)\n  mutate(\n    confidenceAB = n / n1,\n    confidenceBA = n / n2\n    )\n\nhead(all_pairs_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 8\n  item1 item2     n      pc    n1    n2 confidenceAB confidenceBA\n  <int> <int> <int>   <dbl> <int> <int>        <dbl>        <dbl>\n1     1     1   321 0.340     321   321       1             1    \n2     1     2    30 0.0318    321    51       0.0935        0.588\n3     1     3    19 0.0201    321    34       0.0592        0.559\n4     1     4    64 0.0679    321   122       0.199         0.525\n5     1     5    24 0.0255    321    39       0.0748        0.615\n6     1     6     7 0.00742   321    15       0.0218        0.467\n```\n\n\n:::\n:::\n\n\nand the **lift** = P(A AND B) / ( P(A)\\*P(B) ):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall_pairs_summary <- all_pairs_summary %>% \n  left_join(\n    # item1:\n    all_pairs_summary %>% \n      filter(item1 == item2) %>% \n      rename(pc1 = pc) %>% \n      select(item1, pc1),\n      by = \"item1\"\n  ) %>% \n  left_join(\n    # item2:\n    all_pairs_summary %>% \n      filter(item1 == item2) %>% \n      rename(pc2 = pc) %>% \n      select(item2, pc2),\n      by = \"item2\"\n  ) %>% \n  # remove trivial cases of pair of same item:\n  filter(item1 != item2) %>% \n  mutate(\n    indep_prob = pc1 * pc2,\n    lift = pc / (pc1 * pc2)\n    ) %>% \n  rename(support = pc)\n\nhead(all_pairs_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 12\n  item1 item2     n support    n1    n2 confidenceAB confidenceBA   pc1    pc2\n  <int> <int> <int>   <dbl> <int> <int>        <dbl>        <dbl> <dbl>  <dbl>\n1     1     2    30 0.0318    321    51       0.0935        0.588 0.340 0.0541\n2     1     3    19 0.0201    321    34       0.0592        0.559 0.340 0.0361\n3     1     4    64 0.0679    321   122       0.199         0.525 0.340 0.129 \n4     1     5    24 0.0255    321    39       0.0748        0.615 0.340 0.0414\n5     1     6     7 0.00742   321    15       0.0218        0.467 0.340 0.0159\n6     1     7   141 0.150     321   263       0.439         0.536 0.340 0.279 \n# ℹ 2 more variables: indep_prob <dbl>, lift <dbl>\n```\n\n\n:::\n:::\n\n\nHow to read this? Looking at the first row:\n\n-   30 users have liked both items 1 and 2. Amongst all 943 users, this is a joint reach of 3.2%.\n\n-   321 users have liked item 1 (n1). Amongst those, 30 have liked item 2, therefore the confidence on that side is 30 / 321 = 9.35%.\n\n-   51 users have liked item 2 (n2). Amongst those, 30 have liked item 2, therefore the confidence on that side is 30 / 51 = 58.82%.\n\n-   the reach of item 1 is 34.04% and the reach of item 2 is 5.4%, so if both were independent, the probability of liking both would be 34.04% x 5.4% = 1.84%, however we observed this joint probability to be 3.2% (i.e. the support), therefore the lift is 3.2% / 1.84% = 1.72, in other words people who like item 1 are 1.72 times more likely to like item 2 and vice versa.\n\nAs some cells have low number of observations, it's best to set a threshold when analysing the results, for example n = 50. Let's see the pairs of films that are most strongly associated:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall_pairs_summary %>% \n  filter(n1 >= 50, n2 >= 50) %>% \n  # only keep one side of the pairs:\n  filter(item1 < item2) %>% \n  arrange(desc(lift)) %>% \n  head(10) %>% \n  # add film title for item 1:\n  left_join(\n    film_ids %>% \n      rename(\n        item1 = id,\n        film1 = name\n        ),\n    by = \"item1\"\n  ) %>% \n  # add film title for item 2:\n  left_join(\n    film_ids %>% \n      rename(\n        item2 = id,\n        film2 = name\n        ),\n    by = \"item2\"\n  ) %>% \n  select(film1, film2, lift)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 3\n   film1                                                  film2             lift\n   <chr>                                                  <chr>            <dbl>\n 1 Pinocchio (1940)                                       Dumbo (1941)      9.17\n 2 Die Hard 2 (1990)                                      Die Hard: With …  9.13\n 3 Star Trek III: The Search for Spock (1984)             Star Trek: Gene…  8.37\n 4 Wrong Trousers, The (1993)                             Grand Day Out, …  8.30\n 5 Grand Day Out, A (1992)                                Close Shave, A …  8.18\n 6 Die Hard 2 (1990)                                      Under Siege (19…  8.13\n 7 Wallace & Gromit: The Best of Aardman Animation (1996) Grand Day Out, …  7.88\n 8 Madness of King George, The (1994)                     Bullets Over Br…  7.42\n 9 GoldenEye (1995)                                       Die Hard: With …  7.28\n10 Cinderella (1950)                                      Dumbo (1941)      7.27\n```\n\n\n:::\n:::\n\n\nThis makes perfect sense: people who liked Pinocchio are 9 times more likely to also like Dumbo etc.\n\nCheck the films that are most strongly associated with Toy Story:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntoy_story_top10 <- all_pairs_summary %>% \n  filter(n1 >= 50, n2 >= 50) %>% \n  # only keep Toy Story:\n  filter(item1 == 1) %>% \n  arrange(desc(lift)) %>% \n  head(10) %>% \n  # add film title for item 1:\n  left_join(\n    film_ids %>% \n      rename(\n        item1 = id,\n        film1 = name\n        ),\n    by = \"item1\"\n  ) %>% \n  # add film title for item 2:\n  left_join(\n    film_ids %>% \n      rename(\n        item2 = id,\n        film2 = name\n        ),\n    by = \"item2\"\n  ) \n\ntoy_story_top10 %>% \n  select(film1, film2, lift)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 3\n   film1            film2                                        lift\n   <chr>            <chr>                                       <dbl>\n 1 Toy Story (1995) Cinderella (1950)                            2.38\n 2 Toy Story (1995) Dumbo (1941)                                 2.36\n 3 Toy Story (1995) Winnie the Pooh and the Blustery Day (1968)  2.20\n 4 Toy Story (1995) Pinocchio (1940)                             2.19\n 5 Toy Story (1995) Beauty and the Beast (1991)                  2.15\n 6 Toy Story (1995) Mars Attacks! (1996)                         2.14\n 7 Toy Story (1995) Aladdin (1992)                               2.06\n 8 Toy Story (1995) Frighteners, The (1996)                      2.06\n 9 Toy Story (1995) Beavis and Butt-head Do America (1996)       2.06\n10 Toy Story (1995) Grand Day Out, A (1992)                      2.05\n```\n\n\n:::\n:::\n\n\nThe top 10 films most strongly associated with Toy Story are all as we would expect, mostly Disney animation films and films for children.\n\n## visualisation with network graph\n\nTo create an interactive visualisation of the top 10 programmes most strongly associated with Toy Story, we can use R's package `visNetwork`.\n\nFirst we prepare the nodes dataframe, which needs at least the columns `id` and `label`, and optionally the columns `size`, `title` and `color`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# use a scaling factor so the graph displays ok:\nscaling_factor <- 10\n\n# define set of colours that work with visNetwork:\nmy_cols <- c(\n  \"coral\", \"cornflowerblue\",\"darkblue\", \"darkcyan\", \n  \"hotpink\", \"darkgreen\", \"darkkhaki\", \"darkmagenta\", \n  \"darkolivegreen\", \"darkorange\",  \"springgreen\", \"steelblue\",  \n\"thistle\", \"tomato\", \"turquoise\", \"maroon\", \"wheat\", \"yellow\", \"yellowgreen\")\n\n\n# for the nodes we need an id, label and size columns:\nmy_nodes <- rbind(\n  # toy story:\n  toy_story_top10 %>% \n    select(item1, film1) %>% \n    distinct() %>% \n    rename(\n      id = item1,\n      label = film1\n      ),\n  # top 10 films most strongly associated:\n  toy_story_top10 %>% \n    select(item2, film2) %>% \n    rename(\n      id = item2,\n      label = film2\n      )\n) %>% \n  # add reach per item using the dataset of positive ratings:\n  left_join(\n    films_rld %>% \n      rename(id = film_id) %>% \n      group_by(id) %>% \n      summarise(size = n()/scaling_factor),\n    by = \"id\"\n  ) %>% \n  # add the film genres:\n  left_join(\n    film_genres,\n    by = \"id\"\n  ) %>% \n  # add a title in html that will be displayed \n  # when hovering over the node:\n  mutate(\n    color = my_cols[as.numeric(as.factor(genre))],\n    title = paste0(\n    \"<p><b>title = </b>\", label,\"<br>\",\n    \"<b>reach = </b>\", size*scaling_factor, \"<br>\",\n    \"<b>genres = </b>\", genres, \n    \"</p>\") \n  )\n\nmy_nodes %>% \n  select(id, label, size, genres)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 11 × 4\n      id label                                        size genres               \n   <int> <chr>                                       <dbl> <chr>                \n 1     1 Toy Story (1995)                             32.1 animation, childrens…\n 2   415 Cinderella (1950)                             6.8 animation, childrens…\n 3   497 Dumbo (1941)                                  6.1 animation, childrens…\n 4   961 Winnie the Pooh and the Blustery Day (1968)   5.2 animation, childrens \n 5   401 Pinocchio (1940)                              5.9 animation, childrens \n 6   584 Beauty and the Beast (1991)                  13.8 animation, childrens…\n 7   235 Mars Attacks! (1996)                          5.9 action, comedy, sci_…\n 8    95 Aladdin (1992)                               14.4 animation, childrens…\n 9   123 Frighteners, The (1996)                       5   comedy, horror       \n10   240 Beavis and Butt-head Do America (1996)        5   animation, comedy    \n11   189 Grand Day Out, A (1992)                       5.3 animation, comedy    \n```\n\n\n:::\n:::\n\n\nNext, we prepare the dataframe of edges which are the links between items. It needs at least the columns `to` and `from` referencing the item ids:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_edges <- toy_story_top10 %>% \n  rename(\n    to = item2,\n    from = item1\n  ) %>% \n  mutate(title = paste0(\"lift = \", round(lift, digits = 2))) %>% \n  select(to, from, title)\n\n\nhead(my_edges)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n     to  from title      \n  <int> <int> <chr>      \n1   415     1 lift = 2.38\n2   497     1 lift = 2.36\n3   961     1 lift = 2.2 \n4   401     1 lift = 2.19\n5   584     1 lift = 2.15\n6   235     1 lift = 2.14\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvisNetwork(my_nodes, my_edges) %>%\n  visInteraction(navigationButtons = TRUE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"visNetwork html-widget html-fill-item\" id=\"htmlwidget-e2331b73b4ec397522db\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-e2331b73b4ec397522db\">{\"x\":{\"nodes\":{\"id\":[1,415,497,961,401,584,235,95,123,240,189],\"label\":[\"Toy Story (1995)\",\"Cinderella (1950)\",\"Dumbo (1941)\",\"Winnie the Pooh and the Blustery Day (1968)\",\"Pinocchio (1940)\",\"Beauty and the Beast (1991)\",\"Mars Attacks! (1996)\",\"Aladdin (1992)\",\"Frighteners, The (1996)\",\"Beavis and Butt-head Do America (1996)\",\"Grand Day Out, A (1992)\"],\"size\":[32.1,6.8,6.1,5.2,5.9,13.8,5.9,14.4,5,5,5.3],\"title\":[\"<p><b>title = <\\/b>Toy Story (1995)<br><b>reach = <\\/b>321<br><b>genres = <\\/b>animation, childrens, comedy<\\/p>\",\"<p><b>title = <\\/b>Cinderella (1950)<br><b>reach = <\\/b>68<br><b>genres = <\\/b>animation, childrens, musical<\\/p>\",\"<p><b>title = <\\/b>Dumbo (1941)<br><b>reach = <\\/b>61<br><b>genres = <\\/b>animation, childrens, musical<\\/p>\",\"<p><b>title = <\\/b>Winnie the Pooh and the Blustery Day (1968)<br><b>reach = <\\/b>52<br><b>genres = <\\/b>animation, childrens<\\/p>\",\"<p><b>title = <\\/b>Pinocchio (1940)<br><b>reach = <\\/b>59<br><b>genres = <\\/b>animation, childrens<\\/p>\",\"<p><b>title = <\\/b>Beauty and the Beast (1991)<br><b>reach = <\\/b>138<br><b>genres = <\\/b>animation, childrens, musical<\\/p>\",\"<p><b>title = <\\/b>Mars Attacks! (1996)<br><b>reach = <\\/b>59<br><b>genres = <\\/b>action, comedy, sci_fi, war<\\/p>\",\"<p><b>title = <\\/b>Aladdin (1992)<br><b>reach = <\\/b>144<br><b>genres = <\\/b>animation, childrens, comedy, musical<\\/p>\",\"<p><b>title = <\\/b>Frighteners, The (1996)<br><b>reach = <\\/b>50<br><b>genres = <\\/b>comedy, horror<\\/p>\",\"<p><b>title = <\\/b>Beavis and Butt-head Do America (1996)<br><b>reach = <\\/b>50<br><b>genres = <\\/b>animation, comedy<\\/p>\",\"<p><b>title = <\\/b>Grand Day Out, A (1992)<br><b>reach = <\\/b>53<br><b>genres = <\\/b>animation, comedy<\\/p>\"],\"genre\":[\"0_0_1_1_1_0_0_0_0_0_0_0_0_0_0_0_0_0\",\"0_0_1_1_0_0_0_0_0_0_0_1_0_0_0_0_0_0\",\"0_0_1_1_0_0_0_0_0_0_0_1_0_0_0_0_0_0\",\"0_0_1_1_0_0_0_0_0_0_0_0_0_0_0_0_0_0\",\"0_0_1_1_0_0_0_0_0_0_0_0_0_0_0_0_0_0\",\"0_0_1_1_0_0_0_0_0_0_0_1_0_0_0_0_0_0\",\"1_0_0_0_1_0_0_0_0_0_0_0_0_0_1_0_1_0\",\"0_0_1_1_1_0_0_0_0_0_0_1_0_0_0_0_0_0\",\"0_0_0_0_1_0_0_0_0_0_1_0_0_0_0_0_0_0\",\"0_0_1_0_1_0_0_0_0_0_0_0_0_0_0_0_0_0\",\"0_0_1_0_1_0_0_0_0_0_0_0_0_0_0_0_0_0\"],\"genres\":[\"animation, childrens, comedy\",\"animation, childrens, musical\",\"animation, childrens, musical\",\"animation, childrens\",\"animation, childrens\",\"animation, childrens, musical\",\"action, comedy, sci_fi, war\",\"animation, childrens, comedy, musical\",\"comedy, horror\",\"animation, comedy\",\"animation, comedy\"],\"color\":[\"hotpink\",\"darkcyan\",\"darkcyan\",\"darkblue\",\"darkblue\",\"darkcyan\",\"darkkhaki\",\"darkgreen\",\"coral\",\"cornflowerblue\",\"cornflowerblue\"]},\"edges\":{\"to\":[415,497,961,401,584,235,95,123,240,189],\"from\":[1,1,1,1,1,1,1,1,1,1],\"title\":[\"lift = 2.38\",\"lift = 2.36\",\"lift = 2.2\",\"lift = 2.19\",\"lift = 2.15\",\"lift = 2.14\",\"lift = 2.06\",\"lift = 2.06\",\"lift = 2.06\",\"lift = 2.05\"]},\"nodesToDataframe\":true,\"edgesToDataframe\":true,\"options\":{\"width\":\"100%\",\"height\":\"100%\",\"nodes\":{\"shape\":\"dot\"},\"manipulation\":{\"enabled\":false},\"interaction\":{\"navigationButtons\":true,\"zoomSpeed\":1}},\"groups\":null,\"width\":null,\"height\":null,\"idselection\":{\"enabled\":false},\"byselection\":{\"enabled\":false},\"main\":null,\"submain\":null,\"footer\":null,\"background\":\"rgba(0, 0, 0, 0)\",\"tooltipStay\":300,\"tooltipStyle\":\"position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;font-family: verdana;font-size:14px;font-color:#000000;background-color: #f5f4ed;-moz-border-radius: 3px;-webkit-border-radius: 3px;border-radius: 3px;border: 1px solid #808074;box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.2);\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\nThe graph is dynamic:\\\n- click on the nodes to get the number of users who liked the film, and the film's genres.\\\n- click on the edges to get the value of the lift.\\\n- if 2 labels overlap, you can move around the nodes to see them better.\n\nThe size of the bubbles is proportional to the number of viewers and the colors correspond to the group of genres for each film.\n\n# conclusion\n\nIn this post we showed how we can find items that are liked by the same group of people using the Lift, a metric from Market Basket Analysis that measures the deviation from the assumption of independence. The Lift is an easy metric to explain: a lift of 3 means that people who liked item 1 are 3 times more likely to also like item 2 and vice versa.\n\nUsing Network Graphs we can display the results in a visually appealing way.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../../site_libs/vis-9.1.0/vis-network.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/vis-9.1.0/vis-network.min.js\"></script>\n<script src=\"../../site_libs/visNetwork-binding-2.1.2/visNetwork.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}