{
  "hash": "4d4f3f72c2174d3d324e4725a2156670",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Estimating reach and frequency using pmvnorm\"\nauthor:\n  - name: Christel Lacaze Swift\n    affiliation: BBC\n    email: christel.swift@bbc.co.uk\n    attributes:\n        corresponding: true\nabstract: |\n  In a previous article, I showed how to use a simulation from a Gaussian copula to re-create the multivariate distribution of consumed units (time spent, number of films watched etc...) across a population.  In this post, we will see how the same can be done using the multivariate Normal cumulative distribution function.\ndate: 2025-10-13\ncategories: [media measurement, reach and frequency, multivariate modelling, copulas]\nkeywords: \n  - cross media meeasurement\n  - reach and frequency \n  - copulas\ndescription: >\n  Using the cumulative multivariate normal distribution to estimate reach and frequency.\nformat: html\nbibliography: bibliography.bib\ntoc: true\nnumber-sections: true\nimage: \"cumulative_normal.png\"\n---\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(mvtnorm) # to use the multivariate normal distribution rmvnorm and its cumulative distribution pmvnorm\n# make sure to load tidyverse after MASS so that the select function comes from dplyr\nlibrary(tidyverse) \nlibrary(psych) # for the pairs.panels and phi2tetra functions\nlibrary(Matrix) # to use the nearPD function\nlibrary(patchwork) # to display plots side by side\nlibrary(latex2exp) # to use scientific notation on plots\n\noptions(java.parameters = c(\"-XX:+UseConcMarkSweepGC\", \"-Xmx32g\"))\ngc()\n\ntheme_set(theme_classic()) # sets the ggplot theme for the session\noptions(scipen = 999) # so that numbers don't display with the exponent\noptions(dplyr.summarise.inform = FALSE) # to suppress annoying grouping warning\n```\n:::\n\n\n\nIn a previous [post](https://christelswift.github.io/cs_blog/posts/cross_media_with_copulas/), I showed how we can use some marginal distributions (e.g. separate media measurements) and link them with a correlation matrix to derive an estimate of combined reach using a Gaussian copula.  This was done by creating a simulation of 100k data points from the Gaussian copula and by mapping the resulting Normal margins to the observed margins using their quantiles. Then we can simply analyse results based on that simulated dataset and get cross media reach for any time spent threshold, as well as the solus reach from each media.  \n\nIn this post I will show how we can also do this without simulating a dataset, just by using the multivariate Normal cumulative distribution.   As it doesn't have a closed form solution, we will use the convenient `pmvnorm` function from the `mvtnorm` package to estimate the probability $P(X_1 \\in [l_1, u_1], ... , X_n \\in [l_n, u_n])$.  This function implements the methodology described in [@genz]. \n\n![Bivariate Normal Cumulative Distribution](cumulative_normal_plot.png)\n\nFirst I will show how to use the quantile distribution in the univariate case, then the bivariate case using a simulated dataset, and finally using the Bacon and Eggs dataset.  \n\n\n\n# simulated univariate example\n\nIn this previous [post](https://christelswift.github.io/cs_blog/posts/cross_media_with_copulas/), we turned a multivariate continuous simulation into discrete values. To get the probability that our multivariate distribution is in a specific region, for example $P(X_1 = 0, ... , X_n = 0)$, we then used the results from the simulated transformed dataset, but this can also be done using the quantiles of the cumulative continuous distribution. \n\nIn this section we will take the simple example of one variable to demonstrate how we map the values from a random sample from $N(0,1)$ onto any observed discrete distribution.  Then we will show how  to correctly set the bounds of a region of interest with discrete values. \n\nLet's start with a random sample from a Poisson distribution.  We will: \n- derive their observed cumulative distribution,   \n- create a simple univariate normal simulation and   \n- transform it by mapping its continuous values to the observed quantiles in exactly the same way as before.\n\nNote that when we simulate a cross-media dataset from currencies we will not have an observed full dataset, just some observed margins from separate datasets and an empirical correlation matrix from a separate study. The steps described below with the univariate case will seem overly complicated but their only purpose is to illustrate how to correctly set the bounds of the cumulative distribution.  When we move to the multivariate case, this will help to understand how to correctly define the marginal regions of the cumulative multivariate normal distribution.  \n\nFirst, we create a simulated dataset using a Poisson with parameter $\\lambda = 2$, this will be our \"observed\" dataset:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(4)\nsample_size <- 10000\nlambda <- 2\n\ndb <- data.frame(\n  id = 1:sample_size,\n  name = \"x\",\n  value = rpois(n = sample_size, lambda = lambda) \n)\n\nsummary(db)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       id            name               value      \n Min.   :    1   Length:10000       Min.   :0.000  \n 1st Qu.: 2501   Class :character   1st Qu.:1.000  \n Median : 5000   Mode  :character   Median :2.000  \n Mean   : 5000                      Mean   :1.993  \n 3rd Qu.: 7500                      3rd Qu.:3.000  \n Max.   :10000                      Max.   :8.000  \n```\n\n\n:::\n:::\n\n\nCalculate its distribution and cumulative distribution:\n\n::: {.cell}\n\n```{.r .cell-code}\nactual_distr <- db %>% \n  count(value) %>% \n  mutate(\n    pc = n / sample_size,\n    cumpc = cumsum(pc)\n    ) \n\nhead(actual_distr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  value    n     pc  cumpc\n1     0 1367 0.1367 0.1367\n2     1 2690 0.2690 0.4057\n3     2 2702 0.2702 0.6759\n4     3 1842 0.1842 0.8601\n5     4  897 0.0897 0.9498\n6     5  349 0.0349 0.9847\n```\n\n\n:::\n:::\n\n\n\nPlot its observed frequency and cumulative distributions:\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- actual_distr %>% \n  ggplot(aes(x = value, y = pc)) +\n  geom_bar(stat=\"identity\", fill=\"slateblue\") +\n  scale_x_continuous(breaks = 0:8) +\n  scale_y_continuous(labels = scales::percent) +\n  geom_text(vjust = -0.2, size=3, aes(label=scales::percent(pc, accuracy = 1))) +\n  labs(title = \"P(X = k): observed frequencies\")\n\np2 <- actual_distr %>% \n  ggplot(aes(x = value, y = cumpc)) +\n  geom_bar(stat=\"identity\", fill=\"thistle\") +\n  scale_x_continuous(breaks = 0:8) +\n  scale_y_continuous(labels = scales::percent) +\n  geom_text(vjust = -0.2, size=3, aes(label=scales::percent(cumpc, accuracy = 1))) +\n  labs(title = \"F(X): cumulative distribution\")\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\nEach bar on the cumulative distribution on the right shows the observed probability that our variable is below a specified value, for example $F(X=1) = P(X \\leq 1) = P(X=0) + P(X=1)$\n\nNow, as we would do in the multivariate case where we recreate a simulated dataset using just the margins and a correlation matrix, here in the univariate case we start by creating a simulation from a $N(0,1)$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimdata <- data.frame(value = rnorm(n = sample_size))\n\nsummary(simdata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     value          \n Min.   :-4.270416  \n 1st Qu.:-0.684944  \n Median :-0.003042  \n Mean   :-0.009446  \n 3rd Qu.: 0.671714  \n Max.   : 4.049513  \n```\n\n\n:::\n:::\n\n\n**The mapping process:**\\\nGiven an observed cumulative distribution $F(X)$, we map the $p_k = F(X = k)$ to the $N(0,1)$ cumulative distribution:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# extend observed cumulative distribution so that F(X) starts at zero:\nx <- c(-1, actual_distr$value)\ny <- c(0, actual_distr$cumpc)\n\n# observed cumulative distribution:\np1 <- data.frame(x, y) %>% \n  ggplot(aes(x = x, y = y)) + \n  geom_step(col = \"hotpink\") + \n  expand_limits(y = 0) +\n  geom_vline(xintercept = 8, col = \"lightgray\") +\n  geom_hline(yintercept = 1, col = \"lightgray\") +\n  geom_hline(yintercept = actual_distr$cumpc, col = \"lightgray\", linetype = \"dashed\") +\n  scale_y_continuous(breaks = actual_distr$cumpc[1:6]) +\n  labs(\n    title = \"Target: discrete cumulative distribution\",\n    x = TeX(\"$x = F^{-1}(p)$\"), \n    y = TeX(\"$p=F(X)$\")\n    ) +\n  theme(plot.title = element_text(size=10))\n\n\n# cumulative distribution of our simulated N(0,1) :\np2 <- simdata %>% \n  mutate(rounded_value = round(value, digits = 2)) %>% \n  count(rounded_value) %>% \n  mutate(\n    pc = n / sample_size,\n    cumpc = cumsum(pc)\n    ) %>% \n  ggplot(aes(x = rounded_value, y = cumpc)) +\n  geom_line(col = \"hotpink\") +\n  geom_vline(xintercept = 3, col = \"lightgray\") +\n  geom_hline(yintercept = 1, col = \"lightgray\") +\n  geom_hline(yintercept = actual_distr$cumpc, col = \"lightgray\", linetype = \"dashed\") +\n  scale_y_continuous(breaks = actual_distr$cumpc[1:6]) +\n  labs(\n    title = \"Simulation: N(0,1) cumulative distribution\",\n    x = TeX(\"$z = \\\\Phi^{-1}(p)$\"), \n    y = TeX(\"$p=\\\\Phi(Z)$\")\n    ) +\n  theme(plot.title = element_text(size=10))\n\n\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nFor example we see that on the left hand side, the first value corresponding to $P(X = 0)$ is $p = F(X) = 0.1367$, i.e. 13.67% of the observed dataset has the value 0. This is our first critical value: in our simulated dataset on the right, we have to find the value of $z$ such that $p = \\Phi(Z)) = 0.1367$.  To do this we use the **quantile function** which is the inverse of the cumulative distribution function, i.e. for a given cumulative percentage on the y axis, the quantile function gives the corresponding value on the x axis.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(simdata$value, probs = 0.1367)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   13.67% \n-1.119935 \n```\n\n\n:::\n:::\n\n\nso any data point below this threshold in our simulated dataset will be assigned the value of zero: this way, 13.67% of our mapped dataset will be zero, just like in our observed dataset.\n\nThe second step on the right hand side corresponding to $P(X \\leq 1)$ is $p = F(X) = 0.4057$.\\\nIn our simulated dataset, we have to find the value of $z$ such that $p = \\Phi(Z)) = 0.4057$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(simdata$value, probs = 0.4057)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    40.57% \n-0.2364882 \n```\n\n\n:::\n:::\n\n\nso any data point between the 1st and 2nd threshold in our simulated dataset will be assigned the value of 1, etc until we've exhausted all possible values of X.\n\nThe full list of thresholds that we have to apply to the simulated $N(0,1)$ is given by:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(simdata$value, actual_distr$cumpc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    13.67%     40.57%     67.59%     86.01%     94.98%     98.47%     99.56% \n-1.1199352 -0.2364882  0.4550850  1.0847586  1.6398703  2.1387512  2.5406376 \n    99.89%       100% \n 3.0142916  4.0495128 \n```\n\n\n:::\n:::\n\n\n(Note that we use the `quantile` function rather than `pnorm` because we are working with a dataset rather than the underlying distribution.)\n\n\nNow we map the cumulative distributions of this simulated $N(0,1)$ to the observed cumulative distributions:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# make copy so we can replace each column with their corrected values:\ns <- simdata$value\n\n# Find the critical values so we can map the simulated values to these probabilities:\ncrv <- c(-Inf, quantile(s, actual_distr$cumpc))\n\n# Cut the simulated normal data according to the breaks given by the crv table:\ntemp <- cut(\n    s,\n    right = FALSE,\n    include.lowest = FALSE,\n    breaks = crv,\n    labels = actual_distr$value\n  )\n\nsummary(temp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   0    1    2    3    4    5    6    7    8 NA's \n1367 2690 2702 1842  897  349  109   33   10    1 \n```\n\n\n:::\n:::\n\n\nNote that one value is NA which is caused by the rounding of the last critical value. We will have to assign it to the maximum observed value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert the levels back to numeric values:\nsim_temp <-\n    data.frame(value = as.numeric(as.character(temp)))\n\n# if by bad luck we have an NA, this may be to do with rounding of the crv...\n# => replace with the max value:\nsim_temp[is.na(sim_temp)] <- max(actual_distr$value, na.rm = TRUE)\n\n# transform these levels back into our values:\nsim_db <- data.frame(\n  id = 1:sample_size,\n  value = sim_temp$value\n  )\n\nsim_db %>% \n  count(value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  value    n\n1     0 1367\n2     1 2690\n3     2 2702\n4     3 1842\n5     4  897\n6     5  349\n7     6  109\n8     7   33\n9     8   11\n```\n\n\n:::\n:::\n\n\nCompare actual and simulated distributions:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim_distr <- sim_db %>% \n  count(value) %>% \n  mutate(\n    pc = n / sample_size,\n    cumpc = cumsum(pc)\n    ) \n\nrbind(\n  actual_distr %>% \n    mutate(source = \"actual\"), \n  sim_distr %>% \n    mutate(source = \"sim\")\n  ) %>% \n  ggplot(aes(x = value, y = pc, fill = source)) +\n  geom_bar(stat=\"identity\", position = \"dodge\") +\n  scale_fill_manual(values = c(\"slateblue\", \"lightpink\")) +\n  scale_x_continuous(breaks = 0:8) +\n  scale_y_continuous(labels = scales::percent) +\n  geom_text(\n    aes(label=scales::percent(pc, accuracy = 1), fill = source),\n    position = position_dodge(width = 0.8),\n    vjust = -0.2, size = 2.5) +\n  labs(title = \"observed vs simulated frequencies\") +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in geom_text(aes(label = scales::percent(pc, accuracy = 1), fill =\nsource), : Ignoring unknown aesthetics: fill\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n=\\> as expected the observed and simulated frequencies are a perfect match.\n\nNow say we want to calculate the probability that $X \\in [1,2]$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nactual_distr %>% \n  mutate(lead_value = lead(value)) %>% \n  select(value, lead_value, pc, cumpc) %>% \n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  value lead_value     pc  cumpc\n1     0          1 0.1367 0.1367\n2     1          2 0.2690 0.4057\n3     2          3 0.2702 0.6759\n4     3          4 0.1842 0.8601\n5     4          5 0.0897 0.9498\n6     5          6 0.0349 0.9847\n```\n\n\n:::\n:::\n\n\nLooking at the observed cumulative distribution $F(X)$, this would be the area corresponding to $\\text{cumpc} \\leq 0.676$ minus $\\text{cumpc} \\leq 0.137$:\n\n$$P(X \\in [1,2]) = P(X\\leq 2) - P(X=0) = F(X=2) - F(X=0)$$\nLet's write the thresholds for $X$:\n\n::: {.cell}\n\n```{.r .cell-code}\nthresholds <- data.frame(\n  name = \"x\",\n  lower_value = 1,\n  upper_value = 2\n)\n\nthresholds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  name lower_value upper_value\n1    x           1           2\n```\n\n\n:::\n:::\n\n\nI added the lead value to show that this $[1,2]$ region corresponds to the interval between the lead_value = 1 and the value = 2, see in the filter step below: \n\n::: {.cell}\n\n```{.r .cell-code}\n# find the observed cumulative % corresponding to the lower and upper values:\nquantile_bounds <- actual_distr %>% \n  mutate(name = \"x\") %>% \n  mutate(lead_value = lead(value)) %>% \n  inner_join(\n      thresholds,\n      by = \"name\"\n      ) %>% \n    filter(\n      # we need the x value of the actual_distr that is just before the x value \n      # corresponding to the lower_value:\n      lead_value >= lower_value,\n      value <= upper_value\n      ) %>% \n    group_by(name, lower_value, upper_value) %>% \n    summarise(\n      lower_cumpc = min(cumpc),\n      upper_cumpc = max(cumpc)\n    ) %>% \n    mutate(\n      lower_cumpc = ifelse(lower_value <= 0, 0, lower_cumpc)\n    )\n\nquantile_bounds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n# Groups:   name, lower_value [1]\n  name  lower_value upper_value lower_cumpc upper_cumpc\n  <chr>       <dbl>       <dbl>       <dbl>       <dbl>\n1 x               1           2       0.137       0.676\n```\n\n\n:::\n:::\n\n\nIn the univariate case, the answer is simply the difference between upper_cumpc and lower_cumpc, ie $P(X \\in [1,2]) = 53.9\\%$.  When we move to the multivariate case this step will give us the required lower and upper bounds of the cumulative distribution of each observed discrete margin, and it will then make use of the correlation to estimate the corresponding cumulative multivariate distribution.\n\n\n# simulated multivariate example\n\nTo illustrate the multivariate case, we create a bivariate discrete dataset with a specified correlation. We start by creating a bivariate Normal with the given correlation, then we arbitrarily map the margins to discrete values:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(13)\nmy_corr <- 0.8\n\nmy_corr_mat <- matrix(\n  data = c(1, my_corr, my_corr, 1),\n  nrow = 2,\n  byrow = TRUE\n)\n\n# create simulated MVN with that correlation:\nmy_mvn <- rmvnorm(\n  n = sample_size, \n  mean = rep(0, 2), \n  sigma = my_corr_mat\n  ) %>% \n  as.data.frame()\n\ncolnames(my_mvn) <- c(\"x1\", \"x2\")\nhead(my_mvn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          x1          x2\n1  0.3704637 -0.00278030\n2  1.6715265  0.96142140\n3  1.2077354  0.88261110\n4  1.2055505  0.76154478\n5  0.1674273  0.82506694\n6 -0.7715852 -0.07596019\n```\n\n\n:::\n:::\n\n\nLet's use the following margins to get 2 discrete variables with values between 0 and 5:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# to get plausible margins, i'm looking at the frequencies from a binomial distribution\n# with 5 trials (size) and a given probability of success p, \n# so the possible set of values x (number of successes) is between 0 and 5: \nmargins <- rbind(\n  # roughly dbinom(x = 0:5, size = 5, prob = 0.45):\n  data.frame(\n    name = \"x1\",\n    value = 0:5,\n    pc = c(0.05, 0.2, 0.3, 0.25, 0.15, 0.05)\n  ) %>% \n    mutate(cumpc = cumsum(pc)),\n  \n   # roughly dbinom(x = 0:5, size = 5, prob = 0.25):\n  data.frame(\n    name = \"x2\",\n    value = 0:5,\n    pc = c(0.23, 0.38, 0.23, 0.1, 0.05, 0.01)\n  ) %>% \n    mutate(cumpc = cumsum(pc))\n)\n\n# check we add back to 1 by looking at \n# the cumulative distribution at the maximum x value:  \nmargins %>% \n  filter(value == 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  name value   pc cumpc\n1   x1     5 0.05     1\n2   x2     5 0.01     1\n```\n\n\n:::\n:::\n\n\nTransform the simulated MVN so they have these discrete margins:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# make copy so we can replace each column with their corrected values:\nmy_mvn_copy <- my_mvn\n  \nnames <- names(my_mvn)\n\nfor (i in 1:length(names)) {\n  \n  s <- my_mvn[, i]\n  \n  actual_var_distr <- margins %>%\n    filter(name == names[i])\n  \n  # Find the critical values so we can map the simulated values to these probabilities:\n  crv = as.vector(c(min(s), quantile(s, actual_var_distr$cumpc)))\n  \n  # Cut the simulated normal data according to the breaks given by the crv table:\n  temp <- cut(\n    s,\n    right = TRUE,\n    include.lowest = TRUE,\n    breaks = crv,\n    labels = actual_var_distr$value\n  )\n  \n  # Convert the levels back to numeric values:\n  my_mvn_temp <-\n    data.frame(value = as.numeric(as.character(temp)))\n  \n  # if by bad luck we have an NA, this may be to do with rounding of the crv...\n  # => replace with the max value:\n  my_mvn_temp[is.na(my_mvn_temp)] <- max(actual_var_distr$value, na.rm = TRUE)\n  \n  # transform these levels back into our values:\n  my_mvn_copy[, i] <- my_mvn_temp$value\n  \n  }\n  \ndb <- as.data.frame(my_mvn_copy)\nnames(db) <- names\n\nhead(db)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  x1 x2\n1  3  1\n2  5  2\n3  4  2\n4  4  2\n5  3  2\n6  1  1\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(db)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          x1        x2\nx1 1.0000000 0.7359814\nx2 0.7359814 1.0000000\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndb %>% \n  ggplot(aes(x = x1, y = x2)) +\n  geom_jitter(col = \"slateblue\", alpha = 0.7) +\n  labs(title = \"bivariate discrete distribution\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\nPlot the distribution of the margins:\n\n::: {.cell}\n\n```{.r .cell-code}\ndb %>% \n  pivot_longer(cols = x1:x2) %>% \n  group_by(name, value) %>% \n  summarise(n = n()) %>% \n  group_by(name) %>% \n  mutate(pc = n / sum(n)) %>% \n  ggplot(aes(x = value, y = pc)) +\n  geom_bar(stat=\"identity\", fill=\"slateblue\") +\n  scale_x_continuous(breaks = 0:8) +\n  scale_y_continuous(labels = scales::percent) +\n  geom_text(\n    aes(label=scales::percent(pc, accuracy = 1)),\n    vjust = -0.2, size=3\n    ) +\n  facet_wrap(~name) +\n  labs(title = \"bivariate discrete: marginal observed frequencies\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nNow we have a bivariate discrete distribution with a given correlation.  Let's say this is our observed distribution that we want to recreate with a Gaussian copula.   \n\nWe can proceed in the usual way to create our simulated dataset if all we are given are the marginal distributions and a correlation matrix. As the margins are not zero-inflated, I'm just going to use the observed Spearman correlation rather than the Tetrachoric correlation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nactual_distr <- db %>% \n  pivot_longer(all_of(names)) %>% \n  group_by(name, value) %>% \n  summarise(n = n()) %>% \n  group_by(name) %>% \n  mutate(\n    name = factor(name, levels = names),\n    pc = n / sum(n),\n    cumpc = cumsum(pc)\n    ) \n\nhead(actual_distr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n# Groups:   name [1]\n  name  value     n    pc cumpc\n  <fct> <dbl> <int> <dbl> <dbl>\n1 x1        0   500  0.05  0.05\n2 x1        1  2000  0.2   0.25\n3 x1        2  3000  0.3   0.55\n4 x1        3  2500  0.25  0.8 \n5 x1        4  1500  0.15  0.95\n6 x1        5   500  0.05  1   \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobserved_corr <- cor(db, method = \"spearman\")\n\nsimdata <- rmvnorm(\n  n = sample_size, \n  mean = rep(0, nrow(observed_corr)), \n  sigma = observed_corr\n  )\n\nsummary(simdata[1:5,])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       V1                 V2         \n Min.   :-2.85103   Min.   :-2.7641  \n 1st Qu.: 0.13997   1st Qu.:-0.9640  \n Median : 0.53494   Median : 0.2615  \n Mean   :-0.05106   Mean   :-0.2193  \n 3rd Qu.: 0.63108   3rd Qu.: 0.8862  \n Max.   : 1.28975   Max.   : 1.4837  \n```\n\n\n:::\n:::\n\n\nThe result of the simulation is a random sample where the margins are $N(0,1)$ and the correlation is the Spearman correlation of the observed dataset.\n\nNext we map the cumulative distributions of these normal margins to the observed marginal cumulative distributions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# make copy so we can replace each column with their corrected values:\nsim_copy <- simdata\n  \nfor (i in 1:length(names)) {\n  \n  s <- sim_copy[, i]\n  \n  actual_var_distr <- actual_distr %>%\n    filter(name == names[i])\n  \n  # Find the critical values so we can map the simulated values to these probabilities:\n  crv = as.vector(c(min(s), quantile(s, actual_var_distr$cumpc)))\n  \n  # Cut the simulated normal data according to the breaks given by the crv table:\n  temp <- cut(\n    s,\n    right = TRUE,\n    include.lowest = TRUE,\n    breaks = crv,\n    labels = actual_var_distr$value\n  )\n  \n  # Convert the levels back to numeric values:\n  sim_temp <-\n    data.frame(value = as.numeric(as.character(temp)))\n  \n  # if by bad luck we have an NA, this may be to do with rounding of the crv...\n  # => replace with the max value:\n  sim_temp[is.na(sim_temp)] <- max(actual_var_distr$value, na.rm = TRUE)\n  \n  # transform these levels back into our values:\n  sim_copy[, i] <- sim_temp$value\n  \n  }\n  \nsim_db <- as.data.frame(sim_copy)\nnames(sim_db) <- names\n\nhead(sim_db)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  x1 x2\n1  3  2\n2  3  1\n3  4  3\n4  2  0\n5  0  0\n6  3  2\n```\n\n\n:::\n:::\n\n\nCompare simulated margins with actual margins:\n\n::: {.cell}\n\n```{.r .cell-code}\nrbind(\n  actual_distr %>% \n    select(name, value, pc) %>% \n    mutate(source = \"actual\"), \n  sim_db %>% \n    pivot_longer(x1:x2) %>% \n    count(name, value) %>% \n    group_by(name) %>% \n    mutate(pc = n / sum(n)) %>% \n    select(name, value, pc) %>% \n    mutate(source = \"sim\")\n  ) %>% \n  ggplot(aes(x = value, y = pc, fill = source)) +\n  geom_bar(stat=\"identity\", position = \"dodge\") +\n  facet_wrap(~name) +\n  scale_fill_manual(values = c(\"slateblue\", \"lightpink\")) +\n  scale_x_continuous(breaks = 0:8) +\n  scale_y_continuous(labels = scales::percent) +\n  geom_text(\n    aes(label=scales::percent(pc, accuracy = 1), group = source),\n    position = position_dodge(width = 0.8),\n    vjust = -0.2, size = 2.5) +\n  labs(title = \"observed vs simulated frequencies\") +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n=\\> the margins are an exact match as expected.\n\nNow to get $P(X_1 \\in [2,3], X_2 \\in [2,3])$ we can use the simulation:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim_db %>% \n  summarise(pc = sum(x1 >= 2 & x1 <= 3 & x2 >= 2 & x2 <= 3) / nrow(sim_db))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      pc\n1 0.1968\n```\n\n\n:::\n:::\n\n\nor we can use the multivariate equivalent of `pnorm`, i.e. `mvtnorm::pmvnorm` which needs as arguments the lower and upper limits of the region of interest on the margins of the multivariate cumulative distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthresholds <- data.frame(\n  name = c(\"x1\", \"x2\"),\n  lower_value = c(2,2),\n  upper_value = c(3,3)\n)\n\nthresholds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  name lower_value upper_value\n1   x1           2           3\n2   x2           2           3\n```\n\n\n:::\n:::\n\n\nFind the observed cumulative % corresponding to the lower and upper values:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile_bounds <- actual_distr %>% \n  mutate(lead_value = lead(value)) %>% \n  inner_join(\n      thresholds,\n      by = \"name\"\n      ) %>% \n    filter(\n      # we need the x value of the actual_distr that is just before the x value \n      # corresponding to the lower_value:\n      lead_value >= lower_value,\n      value <= upper_value\n      ) %>% \n    group_by(name, lower_value, upper_value) %>% \n    summarise(\n      lower_cumpc = min(cumpc),\n      upper_cumpc = max(cumpc)\n    ) %>% \n    mutate(\n      lower_cumpc = ifelse(lower_value <= 0, 0, lower_cumpc)\n    )\n\nquantile_bounds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n# Groups:   name, lower_value [2]\n  name  lower_value upper_value lower_cumpc upper_cumpc\n  <chr>       <dbl>       <dbl>       <dbl>       <dbl>\n1 x1              2           3        0.25        0.8 \n2 x2              2           3        0.61        0.94\n```\n\n\n:::\n:::\n\nWe now have different bounds of the cumulative distribution for $X_1$ vs $X_2$.  \n\nThese bounds from the discrete cumulative distributions have to be converted to their corresponding quantiles on $N(0,1)$ using the `qnorm` function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile_bounds <- quantile_bounds %>% \n  mutate(\n    lower_phi_quantile = qnorm(lower_cumpc), \n    upper_phi_quantile = qnorm(upper_cumpc) \n  )\n\nquantile_bounds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n# Groups:   name, lower_value [2]\n  name  lower_value upper_value lower_cumpc upper_cumpc lower_phi_quantile\n  <chr>       <dbl>       <dbl>       <dbl>       <dbl>              <dbl>\n1 x1              2           3        0.25        0.8              -0.674\n2 x2              2           3        0.61        0.94              0.279\n# ℹ 1 more variable: upper_phi_quantile <dbl>\n```\n\n\n:::\n:::\n\n\n\nTo understand what we're doing, let's create the corresponding plots for $X_1$:\n\n::: {.cell}\n\n```{.r .cell-code}\nx1_quantile_bounds <- quantile_bounds %>% \n  filter(name == \"x1\")\n\nx1_actual_distr <- actual_distr %>% \n  filter(name == \"x1\")\n\n# extend observed cumulative distribution so that F(X) starts at zero:\nx <- c(-1, x1_actual_distr$value)\ny <- c(0, x1_actual_distr$cumpc)\n\n# observed cumulative distribution:\np1 <- data.frame(x, y) %>% \n  ggplot(aes(x = x, y = y)) + \n  geom_step(col = \"hotpink\") + \n  expand_limits(y = 0) +\n  geom_vline(xintercept = 8, col = \"lightgray\") +\n  geom_hline(yintercept = 1, col = \"lightgray\") +\n  # lower quantile:\n  annotate(\"segment\", \n           x = -1, \n           y = x1_quantile_bounds$lower_cumpc, \n           xend = x1_quantile_bounds$lower_value - 1, \n           yend = x1_quantile_bounds$lower_cumpc,\n           arrow = arrow(ends = \"first\"), \n           linewidth = 0.5, color = \"darkorange\") +\n  annotate(\"segment\", \n           x = x1_quantile_bounds$lower_value - 1, \n           y = x1_quantile_bounds$lower_cumpc, \n           xend = x1_quantile_bounds$lower_value - 1, \n           yend = 0,\n           linewidth = 0.5, color = \"darkorange\") +\n  # upper quantile\n  annotate(\"segment\", \n           x = -1, \n           y = x1_quantile_bounds$upper_cumpc, \n           xend = x1_quantile_bounds$upper_value , \n           yend = x1_quantile_bounds$upper_cumpc,\n           arrow = arrow(ends = \"first\"), \n           linewidth = 0.5, color = \"darkorange\") +\n  annotate(\"segment\", \n           x = x1_quantile_bounds$upper_value , \n           y = x1_quantile_bounds$upper_cumpc, \n           xend = x1_quantile_bounds$upper_value , \n           yend = 0,\n           linewidth = 0.5, color = \"darkorange\") +\n  scale_x_continuous(breaks = c(1, 3)) +\n  scale_y_continuous(breaks = c(x1_quantile_bounds$lower_cumpc, \n                                x1_quantile_bounds$upper_cumpc)) +\n  labs(\n    title = \"observed cumulative distribution\",\n    x = TeX(\"$x = F^{-1}(p)$\"), \n    y = TeX(\"$p=F(X)$\")\n    ) +\n  theme(plot.title = element_text(size=10))\n\n\n# normal cumulative distribution:\nset.seed(13)\np2 <- data.frame(x = rnorm(n = 1000)) %>% \n  mutate(y = pnorm(x)) %>% \n  ggplot(aes(x = x, y = y, group = 1)) +\n  geom_line(col = \"hotpink\") +\n  geom_vline(xintercept = 3, col = \"lightgray\") +\n  geom_hline(yintercept = 1, col = \"lightgray\") +\n  # lower quantile:\n  annotate(\"segment\", \n           x = -3, \n           y = x1_quantile_bounds$lower_cumpc, \n           xend = x1_quantile_bounds$lower_phi_quantile, \n           yend = x1_quantile_bounds$lower_cumpc,\n           linewidth = 0.5, color = \"darkorange\") +\n  annotate(\"segment\", \n           x = x1_quantile_bounds$lower_phi_quantile, \n           y = x1_quantile_bounds$lower_cumpc, \n           xend = x1_quantile_bounds$lower_phi_quantile, \n           yend = 0,\n           arrow = arrow(), \n           linewidth = 0.5, color = \"darkorange\") +\n  # upper quantile\n  annotate(\"segment\", \n           x = -3, \n           y = x1_quantile_bounds$upper_cumpc, \n           xend = x1_quantile_bounds$upper_phi_quantile, \n           yend = x1_quantile_bounds$upper_cumpc,\n           linewidth = 0.5, color = \"darkorange\") +\n  annotate(\"segment\", \n           x = x1_quantile_bounds$upper_phi_quantile, \n           y = x1_quantile_bounds$upper_cumpc, \n           xend = x1_quantile_bounds$upper_phi_quantile, \n           yend = 0,\n           arrow = arrow(), \n           linewidth = 0.5, color = \"darkorange\") +\n  scale_x_continuous(breaks = round(c(x1_quantile_bounds$lower_phi_quantile, \n                                      x1_quantile_bounds$upper_phi_quantile), \n                                    digits = 3)) +\n  scale_y_continuous(breaks = c(x1_quantile_bounds$lower_cumpc, \n                                x1_quantile_bounds$upper_cumpc)) +\n  labs(\n    title = \"Normal cumulative distribution\",\n    x = TeX(\"$x = \\\\Phi^{-1}(p)$\"), \n    y = TeX(\"$p=\\\\Phi(X)$\")\n    ) +\n  theme(plot.title = element_text(size=10))\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\nFor $X_1$ we want to find the cumulative % in the observed distribution such that we are in the region where $X_1 \\in [1,3]$.  These are the y values $(0.25, 0.80)$ on the left hand side.  We then have to find their corresponding quantiles on $N(0,1)$ using the `qnorm` function.  These are $(-0.674, 0.842)$ (see the x values on the plot on the right), and they define the quantile region of the first margin in our cumulative multivariate normal.  \n\nDoing the same exercise with $X_2$ gives the quantile values $(0.279, 1.55)$ on $N(0,1)$ and we can plug them in `mvtnorm::pmvnorm` along with our observed Spearman correlation:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nregion_prob <- pmvnorm(\n      lower = quantile_bounds$lower_phi_quantile,\n      upper = quantile_bounds$upper_phi_quantile,\n      mean = rep(0, length(names)),\n      corr = observed_corr\n    )\n\nregion_prob[1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1969595\n```\n\n\n:::\n:::\n\n\nThis is the same result we found with the simulated dataset: $P(X_1 \\in [2,3], X_2 \\in [2,3]) = 19.7\\%$\n\nLet's put this into a function and compare actual, simulated and pmvnorm results for all possible pairs of values:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndeduplicated_reach_fc <- function(thresholds, actual_distr, sigma){\n  \n  #' Calculate the probability of being in a region \n  #' for example the joint probability that variable 1 is between 1 and 5\n  #' and variable 2 is between 2 and 3:\n  #' P(1 < X1 <= 5, 2 < X2 <= 3)\n  #'\n  #' @param thresholds dataframe with the columns name, lower_value, upper_value\n  #' @param actual_distr dataframe with the columns name, value, pc and cumpc.\n  #' @param sigma named matrix of the correlation between variables.\n  #' @return expected probability.\n  \n  # get the names of the vehicles in the plan:\n  my_vars <- thresholds %>% \n    count(name) %>% \n    pull(name)\n  \n  # get the corresponding correlation matrix:\n  my_corr <- sigma[my_vars, my_vars] \n  \n  # find the observed quantiles corresponding to the lower and upper values:\n  quantile_bounds <- actual_distr %>% \n    group_by(name) %>% \n    mutate(\n      max_value = max(value),\n      lead_value = lead(value)\n      ) %>% \n    inner_join(\n        thresholds,\n        by = \"name\"\n        ) %>% \n      filter(\n        # we need the x value of the actual_distr that is just before the x value \n        # corresponding to the lower_value:\n        lead_value >= lower_value,\n        value <= upper_value\n        ) %>% \n      group_by(name, lower_value, upper_value, max_value) %>% \n      summarise(\n        lower_cumpc = min(cumpc),\n        upper_cumpc = max(cumpc)\n      ) %>% \n      mutate(\n        lower_cumpc = ifelse(lower_value <= 0, 0, lower_cumpc),\n        upper_cumpc = ifelse(upper_value >= max_value, 1, upper_cumpc)\n      ) %>% \n    # find the corresponding quantiles in N(0,1):\n      mutate(\n        lower_phi_quantile = qnorm(lower_cumpc), \n        upper_phi_quantile = qnorm(upper_cumpc) \n      )\n    \n\n  region_prob <- pmvnorm(\n      lower = quantile_bounds$lower_phi_quantile,\n      upper = quantile_bounds$upper_phi_quantile,\n      mean = rep(0, length(my_vars)),\n      corr = my_corr\n    )\n    \n  return(region_prob[1])\n  \n}\n\n\n# test with the example P(2 <= x1 <= 3, 2 <= x1 <= 3):\nthresholds <- data.frame(\n  name = c(\"x1\", \"x2\"), \n  lower_value = c(2, 2), \n  upper_value = c(3, 3)\n  )\n\nresult <- deduplicated_reach_fc(thresholds, actual_distr, sigma = observed_corr)\nresult\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1969595\n```\n\n\n:::\n:::\n\n\nNow for all possible combinations of $X_1, X_2$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nactual_pairs_pc <- db %>% \n  count(x1, x2) %>% \n  mutate(\n    pc = n / sum(n),\n    source = \"actual\"\n    )\n         \nhead(actual_pairs_pc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  x1 x2    n     pc source\n1  0  0  460 0.0460 actual\n2  0  1   40 0.0040 actual\n3  1  0 1115 0.1115 actual\n4  1  1  808 0.0808 actual\n5  1  2   73 0.0073 actual\n6  1  3    4 0.0004 actual\n```\n\n\n:::\n:::\n\n\nSame using the simulated dataset:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_list <- list()\n\nfor(i in 1:nrow(actual_pairs_pc)){\n  \n  result <- sim_db %>% \n  summarise(pc = sum(\n    x1 >= actual_pairs_pc[i,1] \n    & x1 <= actual_pairs_pc[i,1] \n    & x2 >= actual_pairs_pc[i,2]\n    & x2 <= actual_pairs_pc[i,2]\n    ) / nrow(sim_db))\n  \n    \n  my_list[[i]] <- data.frame(\n    x1 = actual_pairs_pc[i,1],\n    x2 = actual_pairs_pc[i,2],\n    pc = result\n  )\n  \n}\n\nsim_pairs_pc <- bind_rows(my_list) %>% \n  mutate(source = \"sim\")\n\nhead(sim_pairs_pc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  x1 x2     pc source\n1  0  0 0.0423    sim\n2  0  1 0.0074    sim\n3  1  0 0.1057    sim\n4  1  1 0.0806    sim\n5  1  2 0.0128    sim\n6  1  3 0.0008    sim\n```\n\n\n:::\n:::\n\n\nSame using `pmvnorm`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_list <- list()\n\nfor(i in 1:nrow(actual_pairs_pc)){\n  \n  thresholds <- data.frame(\n  name = c(\"x1\", \"x2\"), \n  lower_value = c(actual_pairs_pc[i,1], actual_pairs_pc[i,2])\n  ) %>% \n    mutate(upper_value = lower_value)\n    \n  result <- deduplicated_reach_fc(\n  thresholds,\n  actual_distr, \n  sigma = observed_corr\n  )\n  \n  my_list[[i]] <- data.frame(\n    x1 = actual_pairs_pc[i,1],\n    x2 = actual_pairs_pc[i,2],\n    pc = result\n  )\n}\n\n\npmvnorm_pairs_pc <- bind_rows(my_list) %>% \n  mutate(source = \"pmvnorm\")\n\nhead(pmvnorm_pairs_pc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  x1 x2          pc  source\n1  0  0 0.042811875 pmvnorm\n2  0  1 0.006879635 pmvnorm\n3  1  0 0.105379907 pmvnorm\n4  1  1 0.081525202 pmvnorm\n5  1  2 0.011951785 pmvnorm\n6  1  3 0.001056504 pmvnorm\n```\n\n\n:::\n:::\n\n\nCompare actual and sim:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrbind(\n  actual_pairs_pc %>% select(-n),\n  sim_pairs_pc\n) %>% \n  pivot_wider(names_from = source, values_from = pc) %>% \n  ggplot(aes(x = actual, y = sim)) +\n  geom_point(col = \"slateblue\") +\n  geom_abline(intercept = 0, slope = 1, linetype = \"dashed\", col = \"lightgrey\") +\n  scale_x_continuous(labels = scales::percent) +\n  scale_y_continuous(labels = scales::percent) +\n  labs(title = \"actual vs simulated pairs of values\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\nActual and simulated values for $P(X_1 = k_1, X_2 = k_2)$ are very close.  \n\nCompare sim and pmvnorm:\n\n::: {.cell}\n\n```{.r .cell-code}\nrbind(\n  sim_pairs_pc,\n  pmvnorm_pairs_pc\n) %>% \n  pivot_wider(names_from = source, values_from = pc) %>%\n  ggplot(aes(x = sim, y = pmvnorm)) +\n  geom_point(col = \"maroon\") +\n  geom_abline(intercept = 0, slope = 1, linetype = \"dashed\", col = \"lightgrey\") +\n  scale_x_continuous(labels = scales::percent) +\n  scale_y_continuous(labels = scales::percent) +\n  labs(title = \"pmvnorm vs simulated pairs of values\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\nSimulated values and values derived from pmvnorm for $P(X_1 = k_1, X_2 = k_2)$ are basically the same.    \n\n\n\n# Bacon and eggs\n\nNow we can use the same approach with a real dataset, showing the number of times out of four shopping trips when bacon is purchased, and similarly for eggs, see [@baconeggs].  \n\nThe data is a simple frequency table of 548 shopping trips:\n\n::: {.cell}\n\n```{.r .cell-code}\nfreqs <- c(\n  254,34,8,0,1,\n  115,29,8,0,1,\n  42,16,3,4,1,\n  13,6,3,1,0,\n  6,1,1,1,0\n  )\n\nbef <- \n  cbind(\n    expand.grid(\n      bacon = 0:4,\n      eggs = 0:4\n      ),\n    freqs)\n\nhead(bef)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  bacon eggs freqs\n1     0    0   254\n2     1    0    34\n3     2    0     8\n4     3    0     0\n5     4    0     1\n6     0    1   115\n```\n\n\n:::\n:::\n\n\nExpand the dataset so we get one row per shopping trip:\n\n::: {.cell}\n\n```{.r .cell-code}\ndb <- bef %>% \n  uncount(freqs) %>% \n  mutate(id = row_number())\n\nsummary(db)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     bacon             eggs              id       \n Min.   :0.0000   Min.   :0.0000   Min.   :  1.0  \n 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:137.8  \n Median :0.0000   Median :0.0000   Median :274.5  \n Mean   :0.2956   Mean   :0.7117   Mean   :274.5  \n 3rd Qu.:0.0000   3rd Qu.:1.0000   3rd Qu.:411.2  \n Max.   :4.0000   Max.   :4.0000   Max.   :548.0  \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(db[-3])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          bacon      eggs\nbacon 1.0000000 0.2332799\neggs  0.2332799 1.0000000\n```\n\n\n:::\n:::\n\n\n\nFirst we keep a record of the margins for each product:\n\n::: {.cell}\n\n```{.r .cell-code}\nproducts <- names(db)[1:2]\n\nactual_distr <- db %>% \n  pivot_longer(all_of(products)) %>% \n  group_by(name, value) %>% \n  summarise(n = n()) %>% \n  group_by(name) %>% \n  mutate(\n    name = factor(name, levels = products),\n    pc = n / sum(n),\n    cumpc = cumsum(pc)\n    ) \n\nhead(actual_distr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n# Groups:   name [2]\n  name  value     n      pc cumpc\n  <fct> <int> <int>   <dbl> <dbl>\n1 bacon     0   430 0.785   0.785\n2 bacon     1    86 0.157   0.942\n3 bacon     2    23 0.0420  0.984\n4 bacon     3     6 0.0109  0.995\n5 bacon     4     3 0.00547 1    \n6 eggs      0   297 0.542   0.542\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nactual_distr %>% \n  ggplot(aes(x = value, y = pc, fill = name)) +\n  geom_bar(stat = \"identity\") +\n  geom_text(vjust = -0.2, size=3, aes(label=scales::percent(pc, accuracy = 1))) +\n  facet_wrap(~name) +\n  scale_y_continuous(labels = scales::percent) +\n  theme(legend.position = \"none\") +\n  labs(title = \"bacon and eggs: marginal distributions\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n\nSame with the cumulative distributions:\n\n::: {.cell}\n\n```{.r .cell-code}\nactual_distr %>% \n  ggplot(aes(x = value, y = cumpc, fill = name)) +\n  geom_bar(stat = \"identity\") +\n  geom_text(vjust = -0.2, size=3, aes(label=scales::percent(cumpc, accuracy = 1))) +\n  facet_wrap(~name) +\n  scale_y_continuous(labels = scales::percent) +\n  theme(legend.position = \"none\") +\n  labs(title = \"bacon and eggs: cumulative marginal distributions\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\nAs it looks like the data (at least for bacon) has a high incidence of zero values, we will use the Tetrachoric correlation rather than the Spearman correlation.  \n\nTo do this, we first calculate the Phi-coefficients, ie the correlations between the bivariate binary reach.  \n\n::: {.cell}\n\n```{.r .cell-code}\nv1 <- products[1]\nv2 <- products[2]\n\n# transform the 1st product to binary:\nx1 <- db %>% \n    select(!!sym(v1)) %>% \n    rename(v1 = !!sym(v1)) %>% \n    mutate(v1 = ifelse(v1 > 0, 1, 0)) %>% \n    pull(v1)\n  \n# transform the 2nd product to binary:\nx2 <- db %>% \n    select(!!sym(v2)) %>% \n    rename(v2 = !!sym(v2)) %>% \n    mutate(v2 = ifelse(v2 > 0, 1, 0)) %>% \n    pull(v2)\n  \n# calculate the phi coefficient:\nphi_coef <- cor(x1, x2)\n\nphi_coef\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1866927\n```\n\n\n:::\n:::\n\n\nNote that the phi coefficient which is based on the binary versions of the covariates is lower than the correlation which is based on the discrete values of the distributions (ranging from 0 to 4).\n\nUsing $P(X_i=0)$ and the Phi correlation, turn into the Tetrachoric correlation:\n\n::: {.cell}\n\n```{.r .cell-code}\ntcc_coef <- phi2tetra(\n    ph = cor(x1, x2), \n    m = c(mean(x1), mean(x2))\n    )\n\ntcc_coef\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3228499\n```\n\n\n:::\n:::\n\n\nTurn into a matrix:\n\n::: {.cell}\n\n```{.r .cell-code}\ntcc_corr <- matrix(\n  data = c(1, tcc_coef, tcc_coef, 1),\n  byrow = TRUE,\n  nrow = 2,\n  dimnames = list(products, products)\n)\n\ntcc_corr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          bacon      eggs\nbacon 1.0000000 0.3228499\neggs  0.3228499 1.0000000\n```\n\n\n:::\n:::\n\n\n\nRather than running a simulation, we can use the cumulative distribution of the multivariate normal to recover the multivariate distribution. \n\nSay we want to find the probability that eggs and bacon are between 1 and 2 units: \n\n$P( 1 \\leq X_1 \\leq 2, 1 \\leq X_2 \\leq 2)$:\n\n::: {.cell}\n\n```{.r .cell-code}\nthresholds <- data.frame(\n  name = c(\"eggs\", \"bacon\"), \n  lower_value = c(1, 1), \n  upper_value = c(2, 2)\n  )\n\nthresholds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   name lower_value upper_value\n1  eggs           1           2\n2 bacon           1           2\n```\n\n\n:::\n:::\n\n\nAs the observed distribution is discrete, we have to take the lead value as the lower bound:\n\n::: {.cell}\n\n```{.r .cell-code}\nactual_distr %>% \n  mutate(lead_value = lead(value)) %>% \n  filter(\n    name == \"eggs\", \n    # we need the x value before the x value corresponding to the lower_value:\n    lead_value >= 1,\n    value <= 2\n    )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 6\n# Groups:   name [1]\n  name  value     n    pc cumpc lead_value\n  <fct> <int> <int> <dbl> <dbl>      <int>\n1 eggs      0   297 0.542 0.542          1\n2 eggs      1   153 0.279 0.821          2\n3 eggs      2    66 0.120 0.942          3\n```\n\n\n:::\n:::\n\n\n=> for eggs, we'll need to look at the region of the cumulative distribution between [0.542, 0.942].\n\nFind the corresponding empirical quantiles for these lower and upper values:\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile_bounds <- actual_distr %>% \n  group_by(name) %>% \n  mutate(\n    max_value = max(value),\n    lead_value = lead(value)\n  ) %>% \n  inner_join(\n      thresholds,\n      by = \"name\"\n      ) %>% \n   filter(\n        # we need the x value before the x value corresponding to the lower_value:\n        lead_value >= lower_value,\n        value <= upper_value\n        ) %>% \n  group_by(name, lower_value, upper_value, max_value) %>% \n  summarise(\n        lower_cumpc = min(cumpc),\n        upper_cumpc = max(cumpc)\n      ) %>% \n  mutate(\n        lower_cumpc = ifelse(lower_value <= 0, 0, lower_cumpc),\n        upper_cumpc = ifelse(upper_value >= max_value, 1, upper_cumpc)\n      ) %>% \n  mutate(\n    lower_phi_quantile = qnorm(lower_cumpc), \n    upper_phi_quantile = qnorm(upper_cumpc) \n  )\n\nquantile_bounds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 8\n# Groups:   name, lower_value, upper_value [2]\n  name  lower_value upper_value max_value lower_cumpc upper_cumpc\n  <chr>       <dbl>       <dbl>     <int>       <dbl>       <dbl>\n1 bacon           1           2         4       0.785       0.984\n2 eggs            1           2         4       0.542       0.942\n# ℹ 2 more variables: lower_phi_quantile <dbl>, upper_phi_quantile <dbl>\n```\n\n\n:::\n:::\n\n\nThen using `mvtnorm:pmvnorm` we can get the probability corresponding to the relevant region:\n\n::: {.cell}\n\n```{.r .cell-code}\nregion_prob <- pmvnorm(\n      lower = quantile_bounds$lower_phi_quantile,\n      upper = quantile_bounds$upper_phi_quantile,\n      mean = rep(0, length(products)),\n      corr = tcc_corr\n    )\n\nregion_prob[1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1020068\n```\n\n\n:::\n:::\n\n\nCompare with actual:\n\n::: {.cell}\n\n```{.r .cell-code}\nrbind(\n  db %>% \n    filter(\n      bacon >= 1, bacon <= 2, \n      eggs >= 1, eggs <= 2\n      ) %>% \n    summarise(reach_pc = n() / nrow(db)) %>% \n    mutate(source = \"actual\"),\n\n  data.frame(\n    reach_pc = region_prob[1],\n    source = \"pmvnorm\"\n  )\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   reach_pc  source\n1 0.1021898  actual\n2 0.1020068 pmvnorm\n```\n\n\n:::\n:::\n\n\n=> `pmvnorm` matches the actual value for $P( 1 \\leq X_1 \\leq 2, 1 \\leq X_2 \\leq 2)$.\n\nWe can also get this result using the `deduplicated_reach_fc` function defined in section 2:\n\n::: {.cell}\n\n```{.r .cell-code}\nresult <- deduplicated_reach_fc(thresholds, actual_distr, sigma = tcc_corr)\nresult\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1020068\n```\n\n\n:::\n:::\n\n\nTo get the combined null reach $p_{00} = P(X_1 =0, X_2 = 0)$:\n\n::: {.cell}\n\n```{.r .cell-code}\nthresholds <- data.frame(\n  name = c(\"eggs\", \"bacon\"), \n  lower_value = c(-Inf, -Inf), \n  upper_value = c(0, 0)\n  )\n\np_00 <- deduplicated_reach_fc(thresholds, actual_distr, tcc_corr)\np_00\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4635024\n```\n\n\n:::\n:::\n\n\nand then the combined reach is $1-p_{00}$:\n\n::: {.cell}\n\n```{.r .cell-code}\nrbind(\n  db %>% \n  summarise(cross_reach_pc = sum( (bacon + eggs) > 0 ) / nrow(db)) %>% \n  mutate(source = \"actual\"),\n\n  data.frame(\n    cross_reach_pc = 1 - p_00,\n    source = \"pmvnorm\"\n  )\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  cross_reach_pc  source\n1      0.5364964  actual\n2      0.5364976 pmvnorm\n```\n\n\n:::\n:::\n\n\nNow for all possible combinations:\n\n::: {.cell}\n\n```{.r .cell-code}\nactual_pairs_pc <- db %>% \n  count(bacon, eggs) %>% \n  mutate(\n    pc = n / sum(n),\n    source = \"actual\"\n    )\n         \nhead(actual_pairs_pc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  bacon eggs   n         pc source\n1     0    0 254 0.46350365 actual\n2     0    1 115 0.20985401 actual\n3     0    2  42 0.07664234 actual\n4     0    3  13 0.02372263 actual\n5     0    4   6 0.01094891 actual\n6     1    0  34 0.06204380 actual\n```\n\n\n:::\n:::\n\n\nSame using `pmvnorm`:\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_list <- list()\n\nfor(i in 1:nrow(actual_pairs_pc)){\n  \n  thresholds <- data.frame(\n  name = c(\"bacon\", \"eggs\"), \n  lower_value = c(actual_pairs_pc[i,1], actual_pairs_pc[i,2])\n  ) %>% \n    mutate(upper_value = lower_value)\n    \n  result <- deduplicated_reach_fc(\n  thresholds,\n  actual_distr, \n  sigma = tcc_corr\n  )\n  \n  my_list[[i]] <- data.frame(\n    bacon = actual_pairs_pc[i,1],\n    eggs = actual_pairs_pc[i,2],\n    pc = result\n  )\n}\n\n\npmvnorm_pairs_pc <- bind_rows(my_list) %>% \n  mutate(source = \"pmvnorm\")\n\nhead(pmvnorm_pairs_pc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  bacon eggs          pc  source\n1     0    0 0.463502380 pmvnorm\n2     0    1 0.208566981 pmvnorm\n3     0    2 0.079907864 pmvnorm\n4     0    3 0.024594517 pmvnorm\n5     0    4 0.008099791 pmvnorm\n6     1    0 0.061762385 pmvnorm\n```\n\n\n:::\n:::\n\n\nCompare actual and pmvnorm:\n\n::: {.cell}\n\n```{.r .cell-code}\ncompare <- rbind(\n  actual_pairs_pc %>% select(-n),\n  pmvnorm_pairs_pc\n) %>% \n  pivot_wider(names_from = source, values_from = pc)\n\nhead(compare)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  bacon  eggs actual pmvnorm\n  <int> <int>  <dbl>   <dbl>\n1     0     0 0.464  0.464  \n2     0     1 0.210  0.209  \n3     0     2 0.0766 0.0799 \n4     0     3 0.0237 0.0246 \n5     0     4 0.0109 0.00810\n6     1     0 0.0620 0.0618 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncompare %>%\n  ggplot(aes(x = actual, y = pmvnorm)) +\n  geom_point(col = \"maroon\") +\n  geom_abline(intercept = 0, slope = 1, linetype = \"dashed\", col = \"lightgrey\") +\n  scale_x_continuous(labels = scales::percent) +\n  scale_y_continuous(labels = scales::percent) +\n  labs(title = \"actual vs pmvnorm pairs of values\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-55-1.png){width=672}\n:::\n:::\n\n\nIt works!\n\n\nFor a better view of how close the results from pmvnorm are to the actual values, we can look at the log values:\n\n::: {.cell}\n\n```{.r .cell-code}\ncompare %>%\n  ggplot(aes(x = log(actual), y = log(pmvnorm))) +\n  geom_point(col = \"maroon\") +\n  geom_abline(intercept = 0, slope = 1, linetype = \"dashed\", col = \"lightgrey\") +\n  labs(title = \"actual vs pmvnorm pairs of log values\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-56-1.png){width=672}\n:::\n:::\n\n\nLet's zoom in on the values where actual is one value but pmvnorm gives different values:\n\n::: {.cell}\n\n```{.r .cell-code}\ncompare %>% \n  mutate(log_actual = log(actual)) %>% \n  filter(log_actual < -6) %>% \n  inner_join(bef, by = c(\"bacon\", \"eggs\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 6\n  bacon  eggs  actual  pmvnorm log_actual freqs\n  <int> <int>   <dbl>    <dbl>      <dbl> <dbl>\n1     1     4 0.00182 0.00485       -6.31     1\n2     2     4 0.00182 0.00213       -6.31     1\n3     3     3 0.00182 0.00133       -6.31     1\n4     3     4 0.00182 0.000780      -6.31     1\n5     4     0 0.00182 0.00107       -6.31     1\n6     4     1 0.00182 0.00166       -6.31     1\n7     4     2 0.00182 0.00138       -6.31     1\n```\n\n\n:::\n:::\n\n\n=> they all have the same % in the actual dataset because their frequency is just 1.  Although pmvnorm gives different values they are so small (all < 0.5%) it doesn't make any material difference.  \n\nIn the context of an advertising campaign, we could imagine that the products are in fact channels, and the values are the number of impacts.  Then the reach and frequency of the campaign would be fully defined by just summing values across the products:  \n\n\n::: {.cell}\n\n```{.r .cell-code}\ncompare %>% \n  pivot_longer(actual:pmvnorm, names_to = \"source\") %>% \n  mutate(impacts = bacon + eggs) %>% \n  group_by(source, impacts) %>% \n  summarise(pc = sum(value)) %>% \n  ggplot(aes(x = impacts, y = pc, fill = source)) +\n  geom_bar(stat=\"identity\", position = \"dodge\") +\n  scale_fill_manual(values = c(\"slateblue\", \"lightpink\")) +\n  scale_x_continuous(breaks = 0:8) +\n  scale_y_continuous(labels = scales::percent) +\n  geom_text(\n    aes(label=scales::percent(pc, accuracy = 1, fill = source)),\n    position = position_dodge(width = 0.8),\n    vjust = -0.2, size = 2.5) +\n  labs(title = \"actual vs pmvorm frequencies\") +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-58-1.png){width=672}\n:::\n:::\n\n\nThe full distribution of the number of products bought is perfectly preserved.  \n\n\n# Conclusion\n\nIn this post we saw that given just their marginal distributions and a correlation matrix we can recover the entire reach and frequency distribution of a multivariate dataset using the appropriate bounds of the multivariate normal cumulative distribution. This approach is an elegant and stable alternative to creating a simulated dataset.  \n\nIn the context of cross media measurement, it can be used to estimate the cross media reach using the industry standard measurement for each media (i.e. the media currencies), and a correlation matrix from a separate single-source study.   \n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}