{
  "hash": "81e62a314755a5f1450f39f024d4a395",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Weekly reach from daily reach using copulas\"\nauthor:\n  - name: Christel Lacaze Swift\n    affiliation: BBC\n    email: christel.swift@bbc.co.uk\n    attributes:\n        corresponding: true\nabstract: |\n  In a previous article, I showed how to use a simulation from a Gaussian copula to re-create the multivariate distribution of consumed units (time spent, number of films watched etc...) across a population.  In this post, we will see how the same can be done using the multivariate Normal cumulative distribution function.\ndate: 2026-10-06\ncategories: [media measurement, reach and frequency, multivariate modelling, copulas]\nkeywords: \n  - cross media meeasurement\n  - reach and frequency \n  - copulas\ndescription: >\n  Using the multivariate normal distribution to estimate weekly reach from daily reach\nformat: html\ntoc: true\nnumber-sections: true\nimage: \"bivariate_plot.png\"\n---\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(mvtnorm) # to use the multivariate normal distribution rmvnorm and its cumulative distribution pmvnorm\n# make sure to load tidyverse after MASS so that the select function comes from dplyr\nlibrary(tidyverse) \nlibrary(psych) # for the pairs.panels and phi2tetra functions\nlibrary(patchwork) # to display plots side by side\nlibrary(latex2exp) # to use scientific notation on plots\n\noptions(java.parameters = c(\"-XX:+UseConcMarkSweepGC\", \"-Xmx32g\"))\ngc()\n\ntheme_set(theme_classic()) # sets the ggplot theme for the session\noptions(scipen = 999) # so that numbers don't display with the exponent\noptions(dplyr.summarise.inform = FALSE) # to suppress annoying grouping warning\n```\n:::\n\n\n\nHere we show how we can use copulas, more specifically a multi-variate Normal distribution paired with a Tetrachoric correlation, to estimate weekly reach from daily reach. \n\n# the Tetrachoric correlation \n\n## definition\n\nWhen it comes to measuring the association between binary variables, one possible approach is to use the Tetrachoric correlation.  \n\nThis type of correlation relies on the idea that the binary variable actually comes from a **latent normal distribution** that has been dichotomised, such that values below a threshold become one outcome (e.g. 0, or \"fail\") and values above become the other outcome (e.g. 1, or \"pass\").\n\nTake the case of 2 binary variables $X_1$ and $X_2$ with values 0 or 1. We assume these arise from the latent Normal variables $Z_1$ and $Z_2$:\n\n$$\n\\begin{pmatrix}\nZ_1 \\\\\nZ_2\n\\end{pmatrix}\n\\sim N \\left(\n\\begin{pmatrix}\n0 \\\\\n0\n\\end{pmatrix},\n\\begin{pmatrix}\n1 & \\sigma \\\\\n\\sigma & 1\n\\end{pmatrix}\n\\right),\n$$\n\nand then $X_1$ and $X_2$ are derived by applying a threshold to the continuous margins $Z_1$ and $Z_2$:\n\n$$\nX_1 =\n\\begin{cases}\n0 & \\text{if } Z_1 \\leq t_1, \\\\\n1 & \\text{otherwise},\n\\end{cases}\n\\qquad\nX_2 =\n\\begin{cases}\n0 & \\text{if } Z_2 \\leq t_2, \\\\\n1 & \\text{otherwise}.\n\\end{cases}\n$$\n\nThe thresholds $t_1$ and $t_2$ are determined from the observed marginal probabilities:\n\n$$\nP(X_1 = 0) = P(Z_1 \\leq t_1) =  \\Phi(t_1),\n$$\n\n$$\nP(X_2 = 0) = P(Z_1 \\leq t_1) = \\Phi(t_2),\n$$\n\nwhere $\\Phi(\\cdot)$ is the standard normal cumulative distribution function.  \n\nThe **tetrachoric correlation** is then the value of $\\sigma$ that reproduces the observed $2 \\times 2$ contingency table. In particular,\n\n$$\nP(X_1 = 0, X_2 = 0)\n=\nP(Z_1 \\leq t_1, Z_2 \\leq t_2)\n=\n\\Phi_2(t_1, t_2; \\sigma)\n$$\n\nwhere $\\Phi_2(\\cdot,\\cdot;\\sigma)$ denotes the bivariate normal CDF with correlation $\\sigma$.\n\nIn other words, the Tetrachoric correlation is the latent Pearson correlation between $Z_1$ and $Z_2$ that would generate the observed bivariate binary outcomes (i.e. the contingency table) after applying the thresholds to each margin.\n\n\n## illustrative example in 2 dimensions \n\n\nSuppose we asked 100 respondents whether they listened to a radio station over 2 days:  \n- $D_1$ is the reach on day 1   \n- $D_2$ is the reach on day 2   \n\nBuild the contingency table:\n\n::: {.cell}\n\n```{.r .cell-code}\nct <- matrix(\n  data = c(60, 5, 20, 15), \n  nrow = 2, \n  byrow = TRUE,\n  dimnames = list(c(\"d1=0\", \"d1=1\"), c(\"d2=0\", \"d2=1\"))\n  )\n\nct\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     d2=0 d2=1\nd1=0   60    5\nd1=1   20   15\n```\n\n\n:::\n:::\n\nso 60/100 respondents didn't listen on either day and 15/100 listened on both days.  \n\nSame as a dataframe:\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- data.frame(\n  d1 = c(0,0,1,1),\n  d2 = c(0,1,0,1),\n  value = c(60,5,20,15)\n) |> \n  mutate(p = value / sum(value))\n\ndf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  d1 d2 value    p\n1  0  0    60 0.60\n2  0  1     5 0.05\n3  1  0    20 0.20\n4  1  1    15 0.15\n```\n\n\n:::\n:::\n\n\nFrom the contingency table we see that the probability that $D_1 = 0$ and $D_2 = 0$ is 60%.  \n\nCalculate the margins, i.e. the reach% of each day:\n\n::: {.cell}\n\n```{.r .cell-code}\nmargins <- rbind(\n  df %>% \n    group_by(d1) %>% \n    summarise(value = sum(value)) %>%  \n    mutate(\n      cat = d1,\n      day = \"d1\",\n      pc = value / sum(value)\n      ) %>% \n    select(day, cat, pc),\n  \n  df %>% \n    group_by(d2) %>% \n    summarise(value = sum(value)) %>%  \n    mutate(\n      cat = d2,\n      day = \"d2\",\n      pc = value / sum(value)\n      ) %>% \n    select(day, cat, pc)\n) %>% \n  filter(cat == 1)\n\nmargins\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  day     cat    pc\n  <chr> <dbl> <dbl>\n1 d1        1  0.35\n2 d2        1  0.2 \n```\n\n\n:::\n:::\n\nso the reach on day 1 is 35% and on day 2 it's 20%.  \n\nWe can use the function `psych::tetrachoric` to calculate the Tetrachoric correlation from the contingency table:\n\n::: {.cell}\n\n```{.r .cell-code}\ntetr_cor <- tetrachoric(ct)\n\ntetr_cor\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: tetrachoric(x = ct)\ntetrachoric correlation \n[1] 0.67\n\n with tau of \nd1=0 d2=0 \n0.39 0.84 \n```\n\n\n:::\n:::\n\nThis returns both the Tetrachoric correlation and the values of tau.  These correspond to the quintiles for each margin such that:\n\n$P(D1 = 1) = P(Z_1 > \\text{tau}_1) =  1 - P(Z_1 \\leq \\text{tau}_1) = 1 - 0.35$\n\n$P(D2 = 1) = P(Z_2 > \\text{tau}_2) =  1 - P(Z_2 \\leq \\text{tau}_2) = 1 - 0.2$\n\nIn other words, for $D_1$ it shows the threshold value such that 35% of its distribution is to the right of the threshold.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(p = 1 - 0.35)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3853205\n```\n\n\n:::\n:::\n\n\nLikewise for $D_2$ it shows the threshold value such that 20% of its distribution is to the right of the threshold.\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(p = 1 - 0.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8416212\n```\n\n\n:::\n:::\n\n\nThis is what the underlying Normal marginal distributions look like, with their thresholds:\n\n::: {.cell}\n\n```{.r .cell-code}\nthreshold_d1 <- tetr_cor$tau[1]\nthreshold_d2 <- tetr_cor$tau[2]\n\ndf <- data.frame(x = seq(-4, 4, length.out = 500))\ndf$y <- dnorm(df$x)\n\np1 <- ggplot(df, aes(x, y)) +\n  geom_line(colour = \"steelblue\", linewidth = 1.2) +\n  geom_area(data = subset(df, x >= threshold_d1),\n            fill = \"firebrick\", alpha = 0.3) +\n  geom_vline(xintercept = threshold_d1, linetype = \"dashed\",\n             colour = \"firebrick\", linewidth = 1) +\n  annotate(\n    \"text\",\n    x = threshold_d1,\n    y = max(df$y) * 0.9,\n    label = paste0(\"tau = \", round(threshold_d1, 2)),\n    colour = \"firebrick\",\n    hjust = -0.1\n  ) +\n  labs(\n    title = \"Latent distribution for Day 1\",\n    subtitle = \"Day 1 reach = 35%\",\n    x = TeX(\"$Z_1$\"),\n    y = \"Density\"\n  ) \n\np2 <- ggplot(df, aes(x, y)) +\n  geom_line(colour = \"steelblue\", linewidth = 1.2) +\n  geom_area(data = subset(df, x >= threshold_d2),\n            fill = \"firebrick\", alpha = 0.3) +\n  geom_vline(xintercept = threshold_d2, linetype = \"dashed\",\n             colour = \"firebrick\", linewidth = 1) +\n  annotate(\n    \"text\",\n    x = threshold_d2,\n    y = max(df$y) * 0.9,\n    label = paste0(\"tau = \", round(threshold_d2, 2)),\n    colour = \"firebrick\",\n    hjust = -0.1\n  ) +\n  labs(\n    title = \"Latent distribution for Day 2\",\n    subtitle = \"Day 2 reach = 20%\",\n    x = TeX(\"$Z_2$\"),\n    y = \"Density\"\n  ) \n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nThe shaded area under the curve covers 35% of the distribution for day 1 and 20% for day 2.\n\nNow we can look at their underlying bivariate Normal distribution, using their Tetrachoric correlation as sigma:\n\n::: {.cell}\n\n```{.r .cell-code}\n# grid\nx <- seq(-3, 3, length.out = 100)\ny <- seq(-3, 3, length.out = 100)\ngrid <- expand.grid(x = x, y = y)\n\n\nmu <- c(0, 0)\nsigma <- matrix(c(1, tetr_cor$rho, tetr_cor$rho, 1), 2)\n\ngrid$z <- dmvnorm(cbind(grid$x, grid$y), mean = mu, sigma = sigma)\n\nggplot(grid, aes(x, y, z = z)) +\n  geom_contour_filled() +\n  scale_fill_manual(\n    values = colorRampPalette(c(\"white\", \"steelblue\", \"navy\"))(11)\n  ) +\n\n# --- shaded quadrants (exclude bottom-left) ---\nannotate(\"rect\", xmin = threshold_d1, xmax = Inf,\n         ymin = threshold_d2, ymax = Inf,\n         fill = \"red\", alpha = 0.1) +\n\nannotate(\"rect\", xmin = -Inf, xmax = threshold_d1,\n         ymin = threshold_d2, ymax = Inf,\n         fill = \"red\", alpha = 0.1) +\n\nannotate(\"rect\", xmin = threshold_d1, xmax = Inf,\n         ymin = -Inf, ymax = threshold_d2,\n         fill = \"red\", alpha = 0.1) +\n\n\n  # --- threshold lines ---\n  geom_vline(xintercept = threshold_d1, linetype = \"dashed\") +\n  geom_hline(yintercept = threshold_d2, linetype = \"dashed\") +\n\n  scale_x_continuous(breaks = seq(-2,2, by = 1)) +\n  scale_y_continuous(breaks = seq(-2,2, by = 1)) +\n  \n  theme(legend.position = \"none\") +\n  labs(\n    title = \"Latent bivariate distribution for Day 1 and Day 2\", \n    x = TeX(\"$Z_1$\"), y = TeX(\"$Z_2$\")\n    )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nThe shaded area corresponds to the reach on either day, i.e. the combined reach: \n\n$$P(D_1 = 1 | D_2 = 1) = 1 - P(D1 = 0, D2 = 0)$$\n\nWe can calculate the probability $p_{00}$ that $D_1 = 0$ and $D_2 = 0$ with:\n\n$$p_{00} = \\Phi_2(t_1, t_2; \\sigma),$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the joint probability \n# that D1=0 and D2=0:\np_none <- pmvnorm(\n    lower = rep(-Inf, ncol(sigma)), \n    upper = tetr_cor$tau, \n    sigma = sigma\n  )\n\np_none <- as.numeric(p_none)\n\nscales::percent(p_none) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"60%\"\n```\n\n\n:::\n:::\n\n\nThis shows that using a multivariate Normal distribution with the Tetrachoric correlation and the threshold values of each margin, we can retrieve the various probabilities of the contingency table.  \n\n\n# using radio listening dataset\n\nThis dataset was created using R's `synthpop` package and is based on the daily radio listening of 11 stations over a week from RAJAR data in 2022.  It contains 100k synthetic respondents and is available on request.  \n\n::: {.cell}\n\n```{.r .cell-code}\ndb <- read.csv(\"syn_daily_listening_db.csv\")\nsummary(db)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       id           station               day         mins         \n Min.   :     1   Length:7700000     Min.   :1   Min.   :   0.000  \n 1st Qu.: 25001   Class :character   1st Qu.:2   1st Qu.:   0.000  \n Median : 50000   Mode  :character   Median :4   Median :   0.000  \n Mean   : 50000                      Mean   :4   Mean   :   7.493  \n 3rd Qu.: 75000                      3rd Qu.:6   3rd Qu.:   0.000  \n Max.   :100000                      Max.   :7   Max.   :1440.000  \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndb |> \n  summarise(\n    n_rows = n(),\n    n_days = n_distinct(day),\n    n_stations = n_distinct(station),\n    n_resps = n_distinct(id)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   n_rows n_days n_stations n_resps\n1 7700000      7         11  100000\n```\n\n\n:::\n:::\n\n\nWeekly reach for each station:\n\n::: {.cell}\n\n```{.r .cell-code}\nweekly_reach <- db |> \n  group_by(id, station) |> \n  summarise(n_days = sum(mins > 0)) |> \n  group_by(station) |> \n  summarise(reach = sum(n_days > 0)) |> \n  ungroup() |> \n  mutate(reach_pc = reach / n_distinct(db$id))\n\nweekly_reach |> \n  ggplot(aes(x = station, y = reach_pc, fill = station)) +\n  geom_bar(stat = \"identity\") +\n  scale_y_continuous(labels = scales::percent) +\n  labs(title = \"weekly reach by station\") +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\nDaily reach for each station:\n\n::: {.cell}\n\n```{.r .cell-code}\ndaily_reach <- db |> \n  group_by(station, day) |> \n  summarise(reach = sum(mins > 0)) |> \n  ungroup() |> \n  mutate(reach_pc = reach / n_distinct(db$id))\n\ndaily_reach |> \n  ggplot(aes(x = day, y = reach_pc, fill = station)) +\n  geom_bar(stat = \"identity\") +\n  scale_x_continuous(breaks = 1:7) +\n  scale_y_continuous(labels = scales::percent) +\n  facet_wrap(~station, scale = \"free\") +\n  labs(title = \"daily reach by station\") +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaily_freq_distr <- db |> \n  group_by(id, station) |> \n  summarise(n_days = sum(mins > 0)) |> \n  group_by(station, n_days) |> \n  summarise(reach = n()) |> \n  group_by(station) |> \n  mutate(\n    reach_pc = reach / sum(reach),\n    source = \"actual\"\n    )\n\ndaily_freq_distr |> \n  filter(n_days > 0) |> \n  ggplot(aes(x = n_days, y = reach_pc, fill = station)) +\n  geom_bar(stat = \"identity\") +\n  scale_x_continuous(breaks = 1:7) +\n  scale_y_continuous(labels = scales::percent) +\n  facet_wrap(~station, scales = \"free\") +\n  labs(\n    title = \"distribution of the number of days by station\",\n    subtitle = \"excluding n_days = 0\"\n    ) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n=> we see different shapes for the distribution of the number of days listening by users: in particular station 5 shows a strong skew towards users who listen every day of the week, whereas station 1 has a strong incidence of users who only listened on one day out of 7.\n\nIf all we had were the aggregated daily reach for each station and a correlation matrix, could we estimate the weekly reach?\n\n\n## example with one station\n\nLet's walk through the process with the first station.  \n\n::: {.cell}\n\n```{.r .cell-code}\nweekly_reach |> \n  filter(station == \"st1\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  station reach reach_pc\n  <chr>   <int>    <dbl>\n1 st1     13771    0.138\n```\n\n\n:::\n:::\n\nThe actual weekly reach for station 1 is 13.8%.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaily_reach |> \n  filter(station == \"st1\") |> \n  ggplot(aes(x = day, y = reach_pc)) +\n  geom_bar(stat = \"identity\", fill = \"thistle\") +\n  scale_x_continuous(breaks = 1:7) +\n  scale_y_continuous(labels = scales::percent) +\n  geom_text(\n    aes(label = scales::percent(reach_pc, accuracy = 0.1)),\n    size = 3,\n    vjust = -0.3\n    ) +\n  labs(title = \"station 1: daily reach%\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nThe weekly reach $R_w$ is bounded by these 2 values:    \n- in the case where we reach the same people everyday, then it is at least the maximum value of the daily reach levels, so 6.4%.    \n- in the case where we reach entirely new people everyday, then it is at most the sum of the daily reach levels, so 40.5%.   \n\n$$R_w \\in [6.4\\%, 40,5\\%] $$\n\nIf we had no information on the habitual nature of radio listening throughout the week, we could use the assumption of independence between days to estimate the weekly reach:\n\n$$R_w = 1 - \\prod_{d=1}^7 (1 - R_d)$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaily_reach |> \n  filter(station == \"st1\") |> \n  summarise(indep_weekly_reach_pc = 1 - prod(1 - reach_pc))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  indep_weekly_reach_pc\n                  <dbl>\n1                 0.341\n```\n\n\n:::\n:::\n\n=> if we assume the days are independent then the estimated weekly reach for the first station would be 34.1% which is way more than the actual weekly reach of 13.8% and quite close to the maximum possible value.   \n\nTo get the estimate using copulas, we need 2 ingredients:   \n- the daily margins and their corresponding quantile (threshold) on a standard normal curve Z ~ N(0,1).  \n- the Tetrachoric correlation between all 21 possible pairs of days.   \n\nThen we can use them in a multivariate normal cumulative distribution to estimate the value that corresponds to day 1 = 0, day 2 = 0, ... , day 7 = 0.  \n\nStarting with the daily margins, for each day we find the quantile that corresponds to the station's daily reach:\n\n::: {.cell}\n\n```{.r .cell-code}\nthresholds <- daily_reach |> \n  filter(station == \"st1\") |> \n  # Find the threshold points on a standard normal curve Z ~ N(0,1)\n  # These represent the boundaries where 0 becomes 1:\n   mutate(threshold = qnorm(1-reach_pc))\n\nthresholds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 5\n  station   day reach reach_pc threshold\n  <chr>   <int> <int>    <dbl>     <dbl>\n1 st1         1  6360   0.0636      1.53\n2 st1         2  6195   0.0620      1.54\n3 st1         3  6175   0.0618      1.54\n4 st1         4  5933   0.0593      1.56\n5 st1         5  6253   0.0625      1.53\n6 st1         6  5036   0.0504      1.64\n7 st1         7  4534   0.0453      1.69\n```\n\n\n:::\n:::\n\n\nNow we calculate the tetrachoric correlation for all possible pairs of days for station 1.  To do this we need a matrix showing each respondent as a row and each day as a column, and the values are 0 or 1, indicating if the person has listen to the station that day:\n\n::: {.cell}\n\n```{.r .cell-code}\ndays <- paste0(\"d\", 1:7)\n\nusage_mat <- db |> \n  filter(station == \"st1\") |> \n  # the Tetrachoric correlation requires binary data:\n  mutate(\n    day = paste0(\"d\", day),\n    reach_flag = if_else(mins > 0 , 1, 0)\n    ) |> \n  select(id, day, reach_flag) |> \n  pivot_wider(\n    names_from = day, \n    values_from = reach_flag,\n    values_fill = 0\n    ) |> \n  select(all_of(days)) |> \n  as.matrix()\n    \ndim(usage_mat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 100000      7\n```\n\n\n:::\n:::\n\n\nCheck the first 5 respondents:\n\n::: {.cell}\n\n```{.r .cell-code}\nusage_mat[1:5,]  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     d1 d2 d3 d4 d5 d6 d7\n[1,]  1  1  1  1  1  0  0\n[2,]  0  0  0  0  0  0  0\n[3,]  0  1  1  1  0  0  0\n[4,]  0  0  0  0  0  0  0\n[5,]  0  0  0  0  0  0  0\n```\n\n\n:::\n:::\n\n\nCheck we match the daily reach:\n\n::: {.cell}\n\n```{.r .cell-code}\ncolSums(usage_mat)/nrow(usage_mat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     d1      d2      d3      d4      d5      d6      d7 \n0.06360 0.06195 0.06175 0.05933 0.06253 0.05036 0.04534 \n```\n\n\n:::\n:::\n\n\nwhich matches:\n\n::: {.cell}\n\n```{.r .cell-code}\ndaily_reach |> \n  filter(station == \"st1\") |> \n  pull(reach_pc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.06360 0.06195 0.06175 0.05933 0.06253 0.05036 0.04534\n```\n\n\n:::\n:::\n\n\nCalculate the tetrachoric correlation:\n\n::: {.cell}\n\n```{.r .cell-code}\ntetra <- tetrachoric(usage_mat)$rho\n```\n\n```{.r .cell-code}\ntetra\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          d1        d2        d3        d4        d5        d6        d7\nd1 1.0000000 0.9096146 0.8881553 0.8886857 0.8598506 0.7849536 0.7631411\nd2 0.9096146 1.0000000 0.9000754 0.8891819 0.8713600 0.7786639 0.7538051\nd3 0.8881553 0.9000754 1.0000000 0.8899807 0.8716810 0.7773050 0.7681892\nd4 0.8886857 0.8891819 0.8899807 1.0000000 0.8807882 0.7849794 0.7573419\nd5 0.8598506 0.8713600 0.8716810 0.8807882 1.0000000 0.7920922 0.7615531\nd6 0.7849536 0.7786639 0.7773050 0.7849794 0.7920922 1.0000000 0.7946069\nd7 0.7631411 0.7538051 0.7681892 0.7573419 0.7615531 0.7946069 1.0000000\n```\n\n\n:::\n:::\n\n\nUsing this tetrachoric correlation, we can now estimate the probability that d1=0, d2=0, ..., d7=0:\n\n::: {.cell}\n\n```{.r .cell-code}\np_none <- pmvnorm(\n    lower = rep(-Inf, ncol(tetra)), \n    upper = thresholds$threshold, \n    sigma = tetra\n  )\n\np_none <- as.numeric(p_none)\n\n# therefore the estimated weekly reach is 1 - p_none:\n1-p_none\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1388482\n```\n\n\n:::\n:::\n\n\nThis is indeed the actual weekly reach.\n\n\n## repeat for all stations\n\nFor each station we calculate the tetrachoric correlation between all possible pairs of days:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndays <- paste0(\"d\", 1:7)\nstations <- paste0(\"st\", 1:11)\n\nmy_list <- list()\n\nfor(i in 1:length(stations)){\n  \n  thresholds <- daily_reach |> \n   filter(station == stations[i]) |> \n   # Find the threshold points on a standard normal curve Z ~ N(0,1)\n   # These represent the boundaries where 0 becomes 1:\n    mutate(threshold = qnorm(1-reach_pc))\n  \n  indep_weekly_reach_pc <- thresholds |> \n    summarise(weekly_reach_pc = 1 - prod(1-reach_pc)) |> \n    pull(weekly_reach_pc)\n  \n  actual_weekly_reach_pc <- weekly_reach |> \n    filter(station == stations[i]) |> \n    pull(reach_pc)\n  \n  usage_mat <- db |> \n    mutate(\n      reach_flag = if_else(mins > 0, 1, 0),\n      day = paste0(\"d\", day)\n      ) |> \n    filter(station == stations[i]) |>  \n    select(id, day, reach_flag) |> \n    pivot_wider(\n      names_from = day, \n      values_from = reach_flag,\n      values_fill = 0\n      ) |> \n    select(all_of(days)) |> \n    as.matrix()\n  \n  # Calculate the tetrachoric correlation:\n  tetra <- tetrachoric(usage_mat)$rho\n  \n  # Calculate the joint probability that d1=0, d2=0, ..., d7=0\n  p_none <- pmvnorm(\n    lower = rep(-Inf, ncol(tetra)), \n    upper = thresholds$threshold, \n    sigma = tetra\n  )\n  \n  # Convert to a standard numeric value\n  p_none <- as.numeric(p_none)\n\n  my_list[[i]] <- data.frame(\n    station = stations[i],\n    metric = \"weekly_reach_pc\",\n    actual = actual_weekly_reach_pc,\n    copula = 1 - p_none,\n    independence = indep_weekly_reach_pc\n  )\n\n}\n```\n\n```{.r .cell-code}\nresults <- bind_rows(my_list)\nhead(results)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  station          metric  actual     copula independence\n1     st1 weekly_reach_pc 0.13771 0.13891500   0.34111691\n2     st2 weekly_reach_pc 0.01092 0.01063457   0.02298067\n3     st3 weekly_reach_pc 0.30968 0.31371089   0.73551756\n4     st4 weekly_reach_pc 0.04627 0.04581927   0.14703471\n5     st5 weekly_reach_pc 0.24010 0.24628590   0.70690391\n6     st6 weekly_reach_pc 0.04816 0.05051060   0.16086376\n```\n\n\n:::\n:::\n\n\nCompare the results:\n\n::: {.cell}\n\n```{.r .cell-code}\nresults |> \n  pivot_longer(\n    actual:independence, \n    names_to = \"source\", \n    values_to = \"weekly_reach_pc\"\n    ) |> \n  ggplot(aes(x = weekly_reach_pc, y = station, fill = source)) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  scale_x_continuous(\n    labels = scales::percent,\n    expand = expansion(mult = c(0, 0.1))\n    ) +\n  geom_text(\n    aes(label = scales::percent(weekly_reach_pc, accuracy = 0.1)),\n    position = position_dodge(width = 0.9),\n    hjust = -0.1,\n    size = 3\n    ) +\n  labs(\n    title = \"weekly reach results\",\n    x = \"weekly reach %\"\n    ) +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\nThis shows that using the copula approach, the estimated weekly reach is always very close to the actual value.  Using the assumption of independence between days would lead to massively inflated results which don't take into account the repeated nature of listening to a station between days.\n\n\n\n# conclusion\n\nGiven just aggregate values for the daily reach and a correlation matrix, we showed how we can get a realistic estimate of the weekly reach that takes into account the usage overlaps between days.  This approach can be used with the top line results we may get from social media analytics and an inter-day correlation matrix from a separate study.  \n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}